<?xml version="1.0" encoding="utf-8"?>
<page>
<configuration>
	<cp_title><![CDATA[RS visueller<br/>Produktfinder]]></cp_title>
	<cp_subtitle><![CDATA[Finden Sie schnell und einfach Ihr passendes Produkt]]></cp_subtitle>
	<cp_btngo><![CDATA[Zur Suche!]]></cp_btngo>
	<cp_chooseyourselection><![CDATA[Wählen Sie einen Bereich]]></cp_chooseyourselection>
	<cp_titleourservice><![CDATA[Unser Service, Ihre Vorteile]]></cp_titleourservice>
	<cp_copyourservice1><![CDATA[500.000 Produkte aus einer Hand für Sie ab Lager lieferbar - weltweit]]></cp_copyourservice1>
	<cp_copyourservice2><![CDATA[Finden Sie Ihre Produkte schnell und einfach mit unserer Webseite und technischer Unterstützung]]></cp_copyourservice2>
	<cp_copyourservice3><![CDATA[Verhindern Sie unnötige Produktionsausfälle mit schneller Lieferung von unseren weltweiten Lagerstandorten]]></cp_copyourservice3>
	<cp_copyourservice4><![CDATA[Qualität und Sicherheit durch Markenprodukte von über 2.500 Herstellern]]></cp_copyourservice4>
	<cp_copyourservice5><![CDATA[Sie kaufen nur die benötigte Anzahl - keine Mindestbestellmengen]]></cp_copyourservice5>
	<cp_copyourservice6><![CDATA[Verlassen Sie sich auf ein perfektes Preis-Leistungs-Verhältnis ohne langes Suchen]]></cp_copyourservice6>
	<cp_copyourservice7><![CDATA[Zuverlässigkeit von Lieferanten und langfristige Produktverfügbarkeit]]></cp_copyourservice7>
	<cp_btnselect><![CDATA[Auswählen]]></cp_btnselect>
	<cp_hotspot1><![CDATA[Robotertechnik]]></cp_hotspot1>
	<cp_hotspot2><![CDATA[Schaltschrank]]></cp_hotspot2>
	<cp_hotspot3><![CDATA[Förderband]]></cp_hotspot3>
	<cp_hotspot4><![CDATA[Vorratsbehälter]]></cp_hotspot4>
	<cp_submenu1><![CDATA[Zubehör]]></cp_submenu1>
	<cp_submenu2><![CDATA[Messtechnik]]></cp_submenu2>
	<cp_submenu3><![CDATA[Werkzeug und Verbrauchsmaterial]]></cp_submenu3>
	<cp_submenu4><![CDATA[RS Pro]]></cp_submenu4>
</configuration>
<robotics>
<hotspots>
	<entry>
		<idname><![CDATA[robspot2]]></idname>
		<position>
			<left><![CDATA[367]]></left>
			<top><![CDATA[258]]></top>
		</position>
		<items>
			<item>
				<name><![CDATA[Sicherheitszuhaltung]]></name>
				<iconsrc><![CDATA[robotics-02.png]]></iconsrc>
				<link><![CDATA[http://de.rs-online.com/web/c/automation/sicherheitsschaltgerate/sicherheitszuhaltungen/]]></link>
				<description><![CDATA[]]></description>
			</item>
		</items>
	</entry>
	<entry>
		<idname><![CDATA[robspot3]]></idname>
		<position>
			<left><![CDATA[429]]></left>
			<top><![CDATA[380]]></top>
		</position>
		<items>
			<item>
				<name><![CDATA[Bediengeräte Touchpanelversion]]></name>
				<iconsrc><![CDATA[robotics-03.png]]></iconsrc>
				<link><![CDATA[http://de.rs-online.com/web/c/automation/sps-bediengerate-und-datenerfassung/bediengerate-touchpanelversion/]]></link>
				<description><![CDATA[]]></description>
			</item>
		</items>
	</entry>
	<entry>
		<idname><![CDATA[robspot4]]></idname>
		<position>
			<left><![CDATA[688]]></left>
			<top><![CDATA[254]]></top>
		</position>
		<items>
			<item>
				<name><![CDATA[Notausschalter]]></name>
				<iconsrc><![CDATA[robotics-04.png]]></iconsrc>
				<link><![CDATA[http://de.rs-online.com/web/c/automation/sicherheitsschaltgerate/not-aus-schalter/]]></link>
				<description><![CDATA[]]></description>
			</item>
		</items>
	</entry>
	<entry>
		<idname><![CDATA[robspot5]]></idname>
		<position>
			<left><![CDATA[826]]></left>
			<top><![CDATA[123]]></top>
		</position>
		<items>
			<item>
				<name><![CDATA[Signalsäulen]]></name>
				<iconsrc><![CDATA[robotics-05.png]]></iconsrc>
				<link><![CDATA[http://de.rs-online.com/web/c/automation/signalgeber/signalsaulen-komplettgerate/]]></link>
				<description><![CDATA[]]></description>
			</item>
		</items>
	</entry>
	<entry>
		<idname><![CDATA[robspot6]]></idname>
		<position>
			<left><![CDATA[482]]></left>
			<top><![CDATA[478]]></top>
		</position>
		<items>
			<item>
				<name><![CDATA[Sicherheitsrelais]]></name>
				<iconsrc><![CDATA[robotics-06.png]]></iconsrc>
				<link><![CDATA[http://de.rs-online.com/web/c/automation/sicherheitsschaltgerate/sicherheitsrelais/]]></link>
				<description><![CDATA[]]></description>
			</item>
		</items>
	</entry>
	<entry>
		<idname><![CDATA[robspot7]]></idname>
		<position>
			<left><![CDATA[417]]></left>
			<top><![CDATA[424]]></top>
		</position>
		<items>
			<item>
				<name><![CDATA[Tastaturen]]></name>
				<iconsrc><![CDATA[robotics-07.png]]></iconsrc>
				<link><![CDATA[http://de.rs-online.com/web/c/computertechnik-und-peripheriegerate/tastaturen-und-mause/tastaturen/]]></link>
				<description><![CDATA[]]></description>
			</item>
		</items>
	</entry>
	<entry>
		<idname><![CDATA[robspot8]]></idname>
		<position>
			<left><![CDATA[485]]></left>
			<top><![CDATA[407]]></top>
		</position>
		<items>
			<item>
				<name><![CDATA[Schlüsselschalter]]></name>
				<iconsrc><![CDATA[robotics-08.png]]></iconsrc>
				<link><![CDATA[hhttp://de.rs-online.com/web/c/schalter/schlusselschalter-und-zubehor/schlusselschalter/]]></link>
				<description><![CDATA[]]></description>
			</item>
			<item>
				<name><![CDATA[Drucktaster Kompletgeräte]]></name>
				<iconsrc><![CDATA[robotics-09.png]]></iconsrc>
				<link><![CDATA[http://de.rs-online.com/web/c/automation/industrie-drucktaster-leuchtmelder-und-steuerstationen/drucktaster-komplettgerate/]]></link>
				<description><![CDATA[]]></description>
			</item>
		</items>
	</entry>
	<entry>
		<idname><![CDATA[robspot10]]></idname>
		<position>
			<left><![CDATA[457]]></left>
			<top><![CDATA[195]]></top>
		</position>
		<items>
			<item>
				<name><![CDATA[Rohrformteile]]></name>
				<iconsrc><![CDATA[robotics-12.png]]></iconsrc>
				<link><![CDATA[http://de.rs-online.com/web/c/rohrleitungen-rohrverbinder/rohr-schlauch-leitungen/rohrformteile/]]></link>
				<description><![CDATA[]]></description>
			</item>
			<item>
				<name><![CDATA[Faseroptische Sensoren]]></name>
				<iconsrc><![CDATA[robotics-13.png]]></iconsrc>
				<link><![CDATA[http://de.rs-online.com/web/c/automation/sensoren-und-messwandler/faseroptische-sensoren/]]></link>
				<description><![CDATA[]]></description>
			</item>
			<item>
				<name><![CDATA[Pneumatikgreifer]]></name>
				<iconsrc><![CDATA[robotics-10.png]]></iconsrc>
				<link><![CDATA[http://de.rs-online.com/web/c/pneumatik-hydraulik-und-antriebselemente/pneumatik-zylinder-und-antriebe/pneumatik-greifer/]]></link>
				<description><![CDATA[]]></description>
			</item>
		</items>
	</entry>
	<entry>
		<idname><![CDATA[robspot13]]></idname>
		<position>
			<left><![CDATA[422]]></left>
			<top><![CDATA[94]]></top>
		</position>
		<items>
			<item>
				<name><![CDATA[Pneumatik-Gerade Gewinde-zu-Rohr-Adapter]]></name>
				<iconsrc><![CDATA[robotics-15.png]]></iconsrc>
				<link><![CDATA[http://de.rs-online.com/web/c/pneumatik-hydraulik-und-antriebselemente/pneumatik-adapter-fittings-und-verschraubungen/pneumatik-gerade-gewinde-zu-rohr-adapter/]]></link>
				<description><![CDATA[]]></description>
			</item>
			<item>
				<name><![CDATA[Magnetgewinde]]></name>
				<iconsrc><![CDATA[robotics-14.png]]></iconsrc>
				<link><![CDATA[http://de.rs-online.com/web/c/rohrleitungen-rohrverbinder/industriearmaturen-absperrventile/magnetventile/]]></link>
				<description><![CDATA[]]></description>
			</item>
			<item>
				<name><![CDATA[Servomotoren]]></name>
				<iconsrc><![CDATA[robotics-11.png]]></iconsrc>
				<link><![CDATA[http://de.rs-online.com/web/c/automation/antriebstechnik/servomotoren/]]></link>
				<description><![CDATA[]]></description>
			</item>
		</items>
	</entry>
</hotspots>
<accessories>
	<entry>
		<name><![CDATA[Drehantriebe]]></name>
		<link><![CDATA[http://de.rs-online.com/web/c/pneumatik-hydraulik-und-antriebselemente/pneumatik-zylinder-und-antriebe/drehantriebe/
]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Drucksensoren]]></name>
		<link><![CDATA[http://de.rs-online.com/web/c/automation/sensoren-und-messwandler/drucksensoren/
]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Konsolen und Desktopgehäuse]]></name>
		<link><![CDATA[http://de.rs-online.com/web/c/gehause-lagerung-handhabung-transport/gehause/konsolen-und-desktop-gehause/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Leuchtmelder]]></name>
		<link><![CDATA[http://de.rs-online.com/web/c/automation/industrie-drucktaster-leuchtmelder-und-steuerstationen/leuchtmelder-komplettgerate/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Lichtvorhänge]]></name>
		<link><![CDATA[http://de.rs-online.com/web/c/automation/sicherheitsschaltgerate/lichtvorhange/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Manometer]]></name>
		<link><![CDATA[http://de.rs-online.com/web/c/pruf-und-messtechnik/druckmessgerate/manometer-analog/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Optische Nahrungsschalter]]></name>
		<link><![CDATA[http://de.rs-online.com/web/c/automation/sensoren-und-messwandler/optische-naherungsschalter/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Positionsschalter]]></name>
		<link><![CDATA[http://de.rs-online.com/web/c/automation/befehls-und-meldegerate/positionsschalter/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Schrittmotoren]]></name>
		<link><![CDATA[http://de.rs-online.com/web/c/automation/antriebstechnik/schrittmotoren/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Sicherheitsbausteine]]></name>
		<link><![CDATA[http://de.rs-online.com/web/c/automation/sicherheitsschaltgerate/sicherheitsbausteine/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Sicherheitszäune- und Türen]]></name>
		<link><![CDATA[http://de.rs-online.com/web/c/automation/sicherheitsschaltgerate/sicherheits-zaune-und-turen/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Sicherheits-Zweihand-Steuerschalter]]></name>
		<link><![CDATA[http://de.rs-online.com/web/c/automation/sicherheitsschaltgerate/sicherheits-zweihand-steuerschalter/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Signalhupen]]></name>
		<link><![CDATA[http://de.rs-online.com/web/c/automation/signalgeber/signalhupen/]]></link>
		<description><![CDATA[]]></description>
	</entry>
</accessories>
<testandmeasurment>
	<entry>
		<name><![CDATA[Datenlogger]]></name>
		<link><![CDATA[http://de.rs-online.com/web/c/pruf-und-messtechnik/messdatenerfassung-und-datenlogger/datenlogger/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Digitalmultimeter]]></name>
		<link><![CDATA[http://de.rs-online.com/web/c/pruf-und-messtechnik/multimeter-und-zubehor/digital-multimeter/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Installationstester]]></name>
		<link><![CDATA[http://de.rs-online.com/web/c/pruf-und-messtechnik/installationstester-und-zubehor/installationstester/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[IR Thermometer]]></name>
		<link><![CDATA[http://de.rs-online.com/web/c/pruf-und-messtechnik/temperaturmessgerate/ir-thermometer/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Multifunktionskalibratoren]]></name>
		<link><![CDATA[http://de.rs-online.com/web/c/pruf-und-messtechnik/kalibratoren/multifunktionskalibratoren/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Netzqualitatsanalysatoren]]></name>
		<link><![CDATA[http://de.rs-online.com/web/c/pruf-und-messtechnik/netzqualitats-und-leistungsmessgerate/netzqualitatsanalysatoren/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Netzqualitäts-und Leistungsmessgeräte]]></name>
		<link><![CDATA[http://de.rs-online.com/web/c/pruf-und-messtechnik/netzqualitats-und-leistungsmessgerate/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Wärmebildkameras]]></name>
		<link><![CDATA[http://de.rs-online.com/web/c/pruf-und-messtechnik/temperaturmessgerate/warmebildkameras/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Zangenmessgeräte]]></name>
		<link><![CDATA[http://de.rs-online.com/web/c/pruf-und-messtechnik/elektrische-prufgerate/zangenmessgerate/]]></link>
		<description><![CDATA[]]></description>
	</entry>
</testandmeasurment>
<tools>
	<entry>
		<name><![CDATA[Bohrmaschinen]]></name>
		<link><![CDATA[http://de.rs-online.com/web/c/werkzeuge/akku-werkzeuge/akku-bohrmaschinen-bohrschrauber/?searchTerm=Bohrmaschine]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Drehmomentschlüssel]]></name>
		<link><![CDATA[http://de.rs-online.com/web/c/werkzeuge/schraubenschlussel-steckschlussel/drehmomentschlussel/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Hand-Fettpressen]]></name>
		<link><![CDATA[http://de.rs-online.com/web/c/werkzeuge/fettpressen-zubehor/hand-fettpressen/?sra=p&r=t]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Schmierstoffe]]></name>
		<link><![CDATA[http://de.rs-online.com/web/c/reinigungs-und-wartungsmaterialien/fette-ole-und-schmierstoffe/schmierstoffe/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Schraubendreher /-sätze]]></name>
		<link><![CDATA[http://de.rs-online.com/web/c/werkzeuge/schraubendreher-schraubenausdreher/schraubendreher-satze/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Steckschlüssel- Sätze]]></name>
		<link><![CDATA[http://de.rs-online.com/web/c/werkzeuge/schraubenschlussel-steckschlussel/steckschlussel-satze/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Zangen Sätze]]></name>
		<link><![CDATA[http://de.rs-online.com/web/c/werkzeuge/zangen/zangen-satze/?sra=p&r=t]]></link>
		<description><![CDATA[]]></description>
	</entry>
</tools>
<rspro>
	<entry>
		<name><![CDATA[Qualität, Leistung und Mehrwert ohne Kompromisse]]></name>
		<link><![CDATA[http://de.rs-online.com/web/b/rs-pro/
]]></link>
		<description><![CDATA[]]></description>
	</entry>
</rspro>
</robotics>
<conveyorsystems>
<hotspots>
	<entry>
		<idname><![CDATA[convspot2]]></idname>
		<position>
			<left><![CDATA[209]]></left>
			<top><![CDATA[191]]></top>
		</position>
		<items>
			<item>
				<name><![CDATA[Seilzugschalter]]></name>
				<iconsrc><![CDATA[conveyor-02.png]]></iconsrc>
				<link><![CDATA[http://de.rs-online.com/web/c/automation/sicherheitsschaltgerate/seilzugschalter/]]></link>
				<description><![CDATA[]]></description>
			</item>
		</items>
	</entry>
	<entry>
		<idname><![CDATA[convspot3]]></idname>
		<position>
			<left><![CDATA[314]]></left>
			<top><![CDATA[161]]></top>
		</position>
		<items>
			<item>
				<name><![CDATA[LED Leuchtröhren]]></name>
				<iconsrc><![CDATA[conveyor-04.png]]></iconsrc>
				<link><![CDATA[http://de.rs-online.com/web/c/beleuchtung/led-lampen/led-leuchtroehren/]]></link>
				<description><![CDATA[]]></description>
			</item>
		</items>
	</entry>
	<entry>
		<idname><![CDATA[convspot4]]></idname>
		<position>
			<left><![CDATA[394]]></left>
			<top><![CDATA[203]]></top>
		</position>
		<items>
			<item>
				<name><![CDATA[Optische Näherungsschalter]]></name>
				<iconsrc><![CDATA[conveyor-05.png]]></iconsrc>
				<link><![CDATA[http://de.rs-online.com/web/c/automation/sensoren-und-messwandler/optische-naherungsschalter/]]></link>
				<description><![CDATA[]]></description>
			</item>
		</items>
	</entry>
	<entry>
		<idname><![CDATA[convspot5]]></idname>
		<position>
			<left><![CDATA[632]]></left>
			<top><![CDATA[245]]></top>
		</position>
		<items>
			<item>
				<name><![CDATA[Lasttrennschalter]]></name>
				<iconsrc><![CDATA[conveyor-03.png]]></iconsrc>
				<link><![CDATA[http://de.rs-online.com/web/c/automation/befehls-und-meldegerate/lasttrennschalter/]]></link>
				<description><![CDATA[]]></description>
			</item>
		</items>
	</entry>
	<entry>
		<idname><![CDATA[convspot6]]></idname>
		<position>
			<left><![CDATA[488]]></left>
			<top><![CDATA[359]]></top>
		</position>
		<items>
			<item>
				<name><![CDATA[Not-Aus-Schalter]]></name>
				<iconsrc><![CDATA[conveyor-06.png]]></iconsrc>
				<link><![CDATA[http://de.rs-online.com/web/c/automation/sicherheitsschaltgerate/not-aus-schalter/]]></link>
				<description><![CDATA[]]></description>
			</item>
		</items>
	</entry>
	<entry>
		<idname><![CDATA[convspot7]]></idname>
		<position>
			<left><![CDATA[593]]></left>
			<top><![CDATA[348]]></top>
		</position>
		<items>
			<item>
				<name><![CDATA[Frequenzumrichter]]></name>
				<iconsrc><![CDATA[conveyor-07.png]]></iconsrc>
				<link><![CDATA[http://de.rs-online.com/web/c/automation/antriebstechnik/frequenzumrichter/]]></link>
				<description><![CDATA[]]></description>
			</item>
		</items>
	</entry>
	<entry>
		<idname><![CDATA[convspot8]]></idname>
		<position>
			<left><![CDATA[651]]></left>
			<top><![CDATA[314]]></top>
		</position>
		<items>
			<item>
				<name><![CDATA[Barcode Lesegeräte]]></name>
				<iconsrc><![CDATA[conveyor-08.png]]></iconsrc>
				<link><![CDATA[http://de.rs-online.com/web/c/automation/sensoren-und-messwandler/barcode-lesegerate/]]></link>
				<description><![CDATA[]]></description>
			</item>
		</items>
	</entry>
	<entry>
		<idname><![CDATA[convspot9]]></idname>
		<position>
			<left><![CDATA[720]]></left>
			<top><![CDATA[245]]></top>
		</position>
		<items>
			<item>
				<name><![CDATA[Signalsäulen]]></name>
				<iconsrc><![CDATA[robotics-05.png]]></iconsrc>
				<link><![CDATA[http://de.rs-online.com/web/c/automation/signalgeber/signalsaulen-komplettgerate/]]></link>
				<description><![CDATA[]]></description>
			</item>
		</items>
	</entry>
</hotspots>
<accessories>
	<entry>
		<name><![CDATA[Direkt- & Stern-/Dreieck-Motorstarter]]></name>
		<link><![CDATA[http://de.rs-online.com/web/c/automation/antriebstechnik/direkt-stern-dreieck-motorstarter/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Drehgeber]]></name>
		<link><![CDATA[http://de.rs-online.com/web/c/automation/sensoren-und-messwandler/drehgeber/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Gehäuse]]></name>
		<link><![CDATA[http://de.rs-online.com/web/c/gehause-lagerung-handhabung-transport/gehause/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Induktive Nährungsschalter]]></name>
		<link><![CDATA[http://de.rs-online.com/web/c/automation/sensoren-und-messwandler/induktive-naherungsschalter/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Kapazitative Nährungsschalter]]></name>
		<link><![CDATA[http://de.rs-online.com/web/c/automation/sensoren-und-messwandler/kapazitive-naherungsschalter/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Leistungsschutzschalter]]></name>
		<link><![CDATA[http://de.rs-online.com/web/c/automation/stromkreisschutz/leitungsschutzschalter/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Lichtvorhänge]]></name>
		<link><![CDATA[http://de.rs-online.com/web/c/automation/sicherheitsschaltgerate/lichtvorhange/
]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Maschinen-Inspektionsleuchten]]></name>
		<link><![CDATA[http://de.rs-online.com/web/c/beleuchtung/leuchten/maschinen-inspektionsleuchten/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Mehradrige Industriekabel]]></name>
		<link><![CDATA[http://de.rs-online.com/web/c/kabel-leitungen/elektro-industriekabel/mehradrige-industriekabel/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Schütze]]></name>
		<link><![CDATA[http://de.rs-online.com/web/c/automation/schutze/schutze/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Sicherheitsbausteine]]></name>
		<link><![CDATA[http://de.rs-online.com/web/c/automation/sicherheitsschaltgerate/sicherheitsbausteine/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Sicherheitspositionsschalter]]></name>
		<link><![CDATA[http://de.rs-online.com/web/c/automation/sicherheitsschaltgerate/sicherheits-positionsschalter/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Sicherheitszäune und Türen]]></name>
		<link><![CDATA[http://de.rs-online.com/web/c/automation/sicherheitsschaltgerate/sicherheits-zaune-und-turen/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Signalhupen]]></name>
		<link><![CDATA[http://de.rs-online.com/web/c/automation/signalgeber/signalhupen/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Überlastrelais]]></name>
		<link><![CDATA[http://de.rs-online.com/web/c/automation/schutze/uberlastrelais/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Ultraschall-Näherungsschalter]]></name>
		<link><![CDATA[http://de.rs-online.com/web/c/automation/sensoren-und-messwandler/ultraschall-naherungsschalter/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Vision-Sensoren]]></name>
		<link><![CDATA[http://de.rs-online.com/web/c/automation/sensoren-und-messwandler/vision-sensoren/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Wandgehäuse]]></name>
		<link><![CDATA[http://de.rs-online.com/web/c/gehause-lagerung-handhabung-transport/gehause/wandgehause/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Wechselstrommotoren]]></name>
		<link><![CDATA[http://de.rs-online.com/web/c/automation/antriebstechnik/wechselstrommotoren/]]></link>
		<description><![CDATA[]]></description>
	</entry>
</accessories>
<testandmeasurment>
	<entry>
		<name><![CDATA[Digital Multimeter]]></name>
		<link><![CDATA[http://de.rs-online.com/web/c/pruf-und-messtechnik/multimeter-und-zubehor/digital-multimeter/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Installationstester]]></name>
		<link><![CDATA[http://de.rs-online.com/web/c/pruf-und-messtechnik/installationstester-und-zubehor/installationstester/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[IR Thermometer]]></name>
		<link><![CDATA[http://de.rs-online.com/web/c/pruf-und-messtechnik/temperaturmessgerate/ir-thermometer/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Laser-Nivelliergeräte]]></name>
		<link><![CDATA[http://de.rs-online.com/web/c/pruf-und-messtechnik/nivelliergerate-und-winkelmesser/laser-nivelliergerate/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Multifunktionskalibratoren]]></name>
		<link><![CDATA[http://de.rs-online.com/web/c/pruf-und-messtechnik/kalibratoren/multifunktionskalibratoren/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Netzqualitäts- und Leistungsmessgeräte]]></name>
		<link><![CDATA[http://de.rs-online.com/web/c/pruf-und-messtechnik/netzqualitats-und-leistungsmessgerate/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Netzqualitätsanalysatoren]]></name>
		<link><![CDATA[http://de.rs-online.com/web/c/pruf-und-messtechnik/netzqualitats-und-leistungsmessgerate/netzqualitatsanalysatoren/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Tachometer]]></name>
		<link><![CDATA[http://de.rs-online.com/web/c/pruf-und-messtechnik/rotationsprufgerate/tachometer/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Wärmebildkameras]]></name>
		<link><![CDATA[http://de.rs-online.com/web/c/pruf-und-messtechnik/temperaturmessgerate/warmebildkameras/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Zangenmessgeräte]]></name>
		<link><![CDATA[http://de.rs-online.com/web/c/pruf-und-messtechnik/elektrische-prufgerate/zangenmessgerate/]]></link>
		<description><![CDATA[]]></description>
	</entry>
</testandmeasurment>
<tools>
	<entry>
		<name><![CDATA[Drehmomentschlüssel]]></name>
		<link><![CDATA[http://de.rs-online.com/web/c/werkzeuge/schraubenschlussel-steckschlussel/drehmomentschlussel/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Hand-Fettpressen]]></name>
		<link><![CDATA[http://de.rs-online.com/web/c/werkzeuge/fettpressen-zubehor/hand-fettpressen/?sra=p&r=t]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Mechanische-Abzieher]]></name>
		<link><![CDATA[http://de.rs-online.com/web/c/werkzeuge/abzieher-werkzeuge/mechanische-abzieher/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Ratschenschlüssel]]></name>
		<link><![CDATA[http://de.rs-online.com/web/c/werkzeuge/schraubenschlussel-steckschlussel/ratschenschlussel/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Schraubendrehersätze]]></name>
		<link><![CDATA[http://de.rs-online.com/web/c/werkzeuge/schraubendreher-schraubenausdreher/schraubendreher-satze/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Steckschlüsselsätze]]></name>
		<link><![CDATA[http://de.rs-online.com/web/c/werkzeuge/schraubenschlussel-steckschlussel/steckschlussel-satze/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Wasserwaage]]></name>
		<link><![CDATA[http://de.rs-online.com/web/c/pruf-und-messtechnik/nivelliergerate-und-winkelmesser/wasserwaagen-und-neigungsmesser/?searchTerm=Wasserwaage]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Zangen Sätze]]></name>
		<link><![CDATA[http://de.rs-online.com/web/c/werkzeuge/zangen/zangen-satze/?sra=p&r=t]]></link>
		<description><![CDATA[]]></description>
	</entry>
</tools>
<rspro>
	<entry>
		<name><![CDATA[Qualität, Leistung und Mehrwert ohne Kompromisse]]></name>
		<link><![CDATA[http://de.rs-online.com/web/b/rs-pro/
]]></link>
		<description><![CDATA[]]></description>
	</entry>
</rspro>
</conveyorsystems>
<storagetank>
<hotspots>
	<entry>
		<idname><![CDATA[storspot2]]></idname>
		<position>
			<left><![CDATA[238]]></left>
			<top><![CDATA[355]]></top>
		</position>
		<items>
			<item>
				<name><![CDATA[PID Temperaturregler]]></name>
				<iconsrc><![CDATA[storage-02.png]]></iconsrc>
				<link><![CDATA[http://de.rs-online.com/web/c/automation/regeltechnik-und-prozessheizungen/pid-temperaturregler/]]></link>
				<description><![CDATA[]]></description>
			</item>
		</items>
	</entry>
	<entry>
		<idname><![CDATA[storspot3]]></idname>
		<position>
			<left><![CDATA[337]]></left>
			<top><![CDATA[226]]></top>
		</position>
		<items>
			<item>
				<name><![CDATA[Manometer]]></name>
				<iconsrc><![CDATA[storage-03.png]]></iconsrc>
				<link><![CDATA[http://de.rs-online.com/web/c/pruf-und-messtechnik/druckmessgerate/manometer-analog/]]></link>
				<description><![CDATA[]]></description>
			</item>
		</items>
	</entry>
	<entry>
		<idname><![CDATA[storspot4]]></idname>
		<position>
			<left><![CDATA[372]]></left>
			<top><![CDATA[308]]></top>
		</position>
		<items>
			<item>
				<name><![CDATA[Füllstandssensor und Schalter]]></name>
				<iconsrc><![CDATA[storage-04.png]]></iconsrc>
				<link><![CDATA[http://de.rs-online.com/web/c/automation/flussigkeitsmanagement/fullstands-sensor-und-schalter/]]></link>
				<description><![CDATA[]]></description>
			</item>
		</items>
	</entry>
	<entry>
		<idname><![CDATA[storspot5]]></idname>
		<position>
			<left><![CDATA[536]]></left>
			<top><![CDATA[86]]></top>
		</position>
		<items>
			<item>
				<name><![CDATA[Drucksensoren]]></name>
				<iconsrc><![CDATA[storage-06.png]]></iconsrc>
				<link><![CDATA[http://de.rs-online.com/web/c/automation/sensoren-und-messwandler/drucksensoren/]]></link>
				<description><![CDATA[]]></description>
			</item>
		</items>
	</entry>
	<entry>
		<idname><![CDATA[storspot6]]></idname>
		<position>
			<left><![CDATA[618]]></left>
			<top><![CDATA[42]]></top>
		</position>
		<items>
			<item>
				<name><![CDATA[Druckschalter]]></name>
				<iconsrc><![CDATA[storage-07.png]]></iconsrc>
				<link><![CDATA[http://de.rs-online.com/web/c/automation/sensoren-und-messwandler/druckschalter/]]></link>
				<description><![CDATA[]]></description>
			</item>
		</items>
	</entry>
	<entry>
		<idname><![CDATA[storspot7]]></idname>
		<position>
			<left><![CDATA[532]]></left>
			<top><![CDATA[384]]></top>
		</position>
		<items>
			<item>
				<name><![CDATA[Wassermeldesysteme]]></name>
				<iconsrc><![CDATA[storage-09.png]]></iconsrc>
				<link><![CDATA[http://de.rs-online.com/web/c/schutz-und-sicherheitsausrustung-antistatik-reinraum/sicherheitsalarm-systeme-zubehor/wassermeldesysteme/]]></link>
				<description><![CDATA[]]></description>
			</item>
		</items>
	</entry>
	<entry>
		<idname><![CDATA[storspot8]]></idname>
		<position>
			<left><![CDATA[670]]></left>
			<top><![CDATA[338]]></top>
		</position>
		<items>
			<item>
				<name><![CDATA[Kraftmesszellen]]></name>
				<iconsrc><![CDATA[storage-10.png]]></iconsrc>
				<link><![CDATA[http://de.rs-online.com/web/c/automation/sensoren-und-messwandler/kraftmesszellen/]]></link>
				<description><![CDATA[]]></description>
			</item>
		</items>
	</entry>
	<entry>
		<idname><![CDATA[storspot9]]></idname>
		<position>
			<left><![CDATA[724]]></left>
			<top><![CDATA[249]]></top>
		</position>
		<items>
			<item>
				<name><![CDATA[SPS Ein- Ausgangsmodule]]></name>
				<iconsrc><![CDATA[storage-11.png]]></iconsrc>
				<link><![CDATA[http://de.rs-online.com/web/c/automation/sps-bediengerate-und-datenerfassung/sps-ein-ausgangsmodule/]]></link>
				<description><![CDATA[]]></description>
			</item>
		</items>
	</entry>
</hotspots>
<accessories>
	<entry>
		<name><![CDATA[Störungsschalter]]></name>
		<link><![CDATA[http://de.rs-online.com/web/c/automation/flussigkeitsmanagement/durchfluss-sensor-und-schalter/stroemungsschalter]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Füllstandsregler]]></name>
		<link><![CDATA[http://de.rs-online.com/web/c/automation/flussigkeitsmanagement/fullstands-regler/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Thermoelemente]]></name>
		<link><![CDATA[http://de.rs-online.com/web/c/automation/sensoren-und-messwandler/thermoelemente/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Wandgehäuse]]></name>
		<link><![CDATA[http://de.rs-online.com/web/c/gehause-lagerung-handhabung-transport/gehause/wandgehause/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Hydraulikfilter]]></name>
		<link><![CDATA[http://de.rs-online.com/web/c/pneumatik-hydraulik-und-antriebselemente/hydraulik-flussigkeiten-und-filter/hydraulik-filter/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Prozesspumpensteuerung]]></name>
		<link><![CDATA[http://de.rs-online.com/web/c/rohrleitungen-rohrverbinder/prozess-heizungspumpen/prozesspumpen-steuerungen/]]></link>
		<description><![CDATA[]]></description>
	</entry>
</accessories>
<testandmeasurment>
	<entry>
		<name><![CDATA[Druckmessgeräte]]></name>
		<link><![CDATA[http://de.rs-online.com/web/c/pruf-und-messtechnik/druckmessgerate/druckmessgerate/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Zangenmessgeräte]]></name>
		<link><![CDATA[http://de.rs-online.com/web/c/pruf-und-messtechnik/elektrische-prufgerate/zangenmessgerate/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Multifuntionskalibratoren]]></name>
		<link><![CDATA[http://de.rs-online.com/web/c/pruf-und-messtechnik/kalibratoren/multifunktionskalibratoren/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Gasdetektoren]]></name>
		<link><![CDATA[http://de.rs-online.com/web/c/pruf-und-messtechnik/luft-gas-und-stromungsmessgerate/gasdetektoren/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Digital Multimeter]]></name>
		<link><![CDATA[http://de.rs-online.com/web/c/pruf-und-messtechnik/multimeter-und-zubehor/digital-multimeter/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Netzqualitäts- und Leistungsmessgeräte]]></name>
		<link><![CDATA[http://de.rs-online.com/web/c/pruf-und-messtechnik/netzqualitats-und-leistungsmessgerate/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Netzqualitätsanalysatoren]]></name>
		<link><![CDATA[http://de.rs-online.com/web/c/pruf-und-messtechnik/netzqualitats-und-leistungsmessgerate/netzqualitatsanalysatoren/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[IR Thermometer]]></name>
		<link><![CDATA[http://de.rs-online.com/web/c/pruf-und-messtechnik/temperaturmessgerate/ir-thermometer/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Wärmebildkameras]]></name>
		<link><![CDATA[http://de.rs-online.com/web/c/pruf-und-messtechnik/temperaturmessgerate/warmebildkameras/]]></link>
		<description><![CDATA[]]></description>
	</entry>
</testandmeasurment>
<tools>
	<entry>
		<name><![CDATA[Taschenlampen]]></name>
		<link><![CDATA[http://de.rs-online.com/web/c/beleuchtung/taschen-handlampen/taschenlampen/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Rohr, Gewinde und Dichtmittel]]></name>
		<link><![CDATA[http://de.rs-online.com/web/c/klebstoffe-dichtmittel-klebebander/dichtmittel/rohr-gewinde-dichtmittel/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Einweghandschuhe]]></name>
		<link><![CDATA[http://de.rs-online.com/web/c/schutz-und-sicherheitsausrustung-antistatik-reinraum/korperschutz-kleidung-und-schuhwerk/einweghandschuhe/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Bohrmaschinen]]></name>
		<link><![CDATA[http://de.rs-online.com/web/c/werkzeuge/akku-werkzeuge/akku-bohrmaschinen-bohrschrauber/?searchTerm=Bohrmaschine]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Bohrer-, Gewindebohrer /-sätze]]></name>
		<link><![CDATA[http://de.rs-online.com/web/c/werkzeuge/gewinde-schneidzeug/bohrer-gewindebohrer-satze/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Schraubendreher /-sätze]]></name>
		<link><![CDATA[http://de.rs-online.com/web/c/werkzeuge/schraubendreher-schraubenausdreher/schraubendreher-satze/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Wasserpumpenzangen]]></name>
		<link><![CDATA[http://de.rs-online.com/web/c/werkzeuge/zangen/wasserpumpenzangen/
]]></link>
		<description><![CDATA[]]></description>
	</entry>
</tools>
<rspro>
	<entry>
		<name><![CDATA[Qualität, Leistung und Mehrwert ohne Kompromisse]]></name>
		<link><![CDATA[http://de.rs-online.com/web/b/rs-pro/
]]></link>
		<description><![CDATA[]]></description>
	</entry>
</rspro>
</storagetank>
<controlcabinet>
<hotspots>
	<entry>
		<idname><![CDATA[contrspot2]]></idname>
		<position>
			<left><![CDATA[198]]></left>
			<top><![CDATA[285]]></top>
		</position>
		<items>
			<item>
				<name><![CDATA[Lasttrennschalter]]></name>
				<iconsrc><![CDATA[controlcabinet-02.png]]></iconsrc>
				<link><![CDATA[http://de.rs-online.com/web/c/automation/befehls-und-meldegerate/lasttrennschalter/]]></link>
				<description><![CDATA[]]></description>
			</item>
		</items>
	</entry>
	<entry>
		<idname><![CDATA[contrspot3]]></idname>
		<position>
			<left><![CDATA[495]]></left>
			<top><![CDATA[42]]></top>
		</position>
		<items>
			<item>
				<name><![CDATA[Signalsäulen]]></name>
				<iconsrc><![CDATA[controlcabinet-10.png]]></iconsrc>
				<link><![CDATA[http://de.rs-online.com/web/c/automation/signalgeber/signalsaulen/]]></link>
				<description><![CDATA[]]></description>
			</item>
		</items>
	</entry>
	<entry>
		<idname><![CDATA[contrspot4]]></idname>
		<position>
			<left><![CDATA[582]]></left>
			<top><![CDATA[147]]></top>
		</position>
		<items>
			<item>
				<name><![CDATA[PC Datenerfassung]]></name>
				<iconsrc><![CDATA[controlcabinet-11.png]]></iconsrc>
				<link><![CDATA[http://de.rs-online.com/web/c/automation/sps-bediengerate-und-datenerfassung/pc-datenerfassung/]]></link>
				<description><![CDATA[]]></description>
			</item>
			<item>
				<name><![CDATA[Signalaufbereitung]]></name>
				<iconsrc><![CDATA[controlcabinet-12.png]]></iconsrc>
				<link><![CDATA[http://de.rs-online.com/web/c/automation/steuerrelais/signalaufbereitung/]]></link>
				<description><![CDATA[]]></description>
			</item>
			<item>
				<name><![CDATA[Transformatoren für DIN-Schienen- & Tafelmontage]]></name>
				<iconsrc><![CDATA[controlcabinet-13.png]]></iconsrc>
				<link><![CDATA[http://de.rs-online.com/web/c/stromversorgungen-transformatoren/transformatoren/transformatoren-fur-din-schienen-tafelmontage/]]></link>
				<description><![CDATA[]]></description>
			</item>
		</items>
	</entry>
	<entry>
		<idname><![CDATA[contrspot5]]></idname>
		<position>
			<left><![CDATA[686]]></left>
			<top><![CDATA[196]]></top>
		</position>
		<items>
			<item>
				<name><![CDATA[Industrie Hubs und Switches]]></name>
				<iconsrc><![CDATA[controlcabinet-14.png]]></iconsrc>
				<link><![CDATA[http://de.rs-online.com/web/c/computertechnik-und-peripheriegerate/netzwerk-und-konnektivitat/industrie-hubs-und-switches/]]></link>
				<description><![CDATA[]]></description>
			</item>
		</items>
	</entry>
	<entry>
		<idname><![CDATA[contrspot6]]></idname>
		<position>
			<left><![CDATA[753]]></left>
			<top><![CDATA[226]]></top>
		</position>
		<items>
			<item>
				<name><![CDATA[Prozessmodule]]></name>
				<iconsrc><![CDATA[controlcabinet-15.png]]></iconsrc>
				<link><![CDATA[http://de.rs-online.com/web/c/automation/sps-bediengerate-und-datenerfassung/prozessmodule/]]></link>
				<description><![CDATA[]]></description>
			</item>
		</items>
	</entry>
	<entry>
		<idname><![CDATA[contrspot7]]></idname>
		<position>
			<left><![CDATA[605]]></left>
			<top><![CDATA[244]]></top>
		</position>
		<items>
			<item>
				<name><![CDATA[Motorschutzschalter]]></name>
				<iconsrc><![CDATA[controlcabinet-17.png]]></iconsrc>
				<link><![CDATA[http://de.rs-online.com/web/c/automation/antriebstechnik/motorschutzschalter/]]></link>
				<description><![CDATA[]]></description>
			</item>
			<item>
				<name><![CDATA[Schütze]]></name>
				<iconsrc><![CDATA[controlcabinet-18.png]]></iconsrc>
				<link><![CDATA[http://de.rs-online.com/web/c/automation/schutze/schutze/]]></link>
				<description><![CDATA[]]></description>
			</item>
			<item>
				<name><![CDATA[Frequenzumrichter]]></name>
				<iconsrc><![CDATA[controlcabinet-19.png]]></iconsrc>
				<link><![CDATA[http://de.rs-online.com/web/c/automation/antriebstechnik/frequenzumrichter/]]></link>
				<description><![CDATA[]]></description>
			</item>
		</items>
	</entry>
	<entry>
		<idname><![CDATA[contrspot8]]></idname>
		<position>
			<left><![CDATA[688]]></left>
			<top><![CDATA[286]]></top>
		</position>
		<items>
			<item>
				<name><![CDATA[Leitungsschutzschalter]]></name>
				<iconsrc><![CDATA[controlcabinet-20.png]]></iconsrc>
				<link><![CDATA[http://de.rs-online.com/web/c/automation/stromkreisschutz/leitungsschutzschalter/]]></link>
				<description><![CDATA[]]></description>
			</item>
		</items>
	</entry>
	<entry>
		<idname><![CDATA[contrspot9]]></idname>
		<position>
			<left><![CDATA[637]]></left>
			<top><![CDATA[329]]></top>
		</position>
		<items>
			<item>
				<name><![CDATA[Zeitrelais]]></name>
				<iconsrc><![CDATA[controlcabinet-23.png]]></iconsrc>
				<link><![CDATA[http://de.rs-online.com/web/c/automation/zeitrelais-und-zahler/zeitrelais/]]></link>
				<description><![CDATA[]]></description>
			</item>
			<item>
				<name><![CDATA[Interface Relaismodule]]></name>
				<iconsrc><![CDATA[controlcabinet-24.png]]></iconsrc>
				<link><![CDATA[http://de.rs-online.com/web/c/relais/interfacerelais-module-und-zubehor/interface-relaismodule/]]></link>
				<description><![CDATA[]]></description>
			</item>
			<item>
				<name><![CDATA[Sicherheitsrelais]]></name>
				<iconsrc><![CDATA[controlcabinet-25.png]]></iconsrc>
				<link><![CDATA[http://de.rs-online.com/web/c/automation/sicherheitsschaltgerate/sicherheitsrelais/]]></link>
				<description><![CDATA[]]></description>
			</item>
		</items>
	</entry>
	<entry>
		<idname><![CDATA[contrspot10]]></idname>
		<position>
			<left><![CDATA[716]]></left>
			<top><![CDATA[360]]></top>
		</position>
		<items>
			<item>
				<name><![CDATA[SPS Zentralbaugruppen]]></name>
				<iconsrc><![CDATA[controlcabinet-26.png]]></iconsrc>
				<link><![CDATA[http://de.rs-online.com/web/c/automation/sps-bediengerate-und-datenerfassung/sps-zentralbaugruppen/]]></link>
				<description><![CDATA[]]></description>
			</item>
			<item>
				<name><![CDATA[DIN Schienenklemmen]]></name>
				<iconsrc><![CDATA[controlcabinet-27.png]]></iconsrc>
				<link><![CDATA[http://de.rs-online.com/web/c/steckverbinder/reihenklemmen-und-anschlussblocke/din-schienenklemmen-ohne-sicherung/]]></link>
				<description><![CDATA[]]></description>
			</item>
		</items>
	</entry>
	<entry>
		<idname><![CDATA[contrspot11]]></idname>
		<position>
			<left><![CDATA[513]]></left>
			<top><![CDATA[321]]></top>
		</position>
		<items>
			<item>
				<name><![CDATA[Filterlüfter]]></name>
				<iconsrc><![CDATA[controlcabinet-25.png]]></iconsrc>
				<link><![CDATA[http://de.rs-online.com/web/c/heizung-luftung-klimatechnik/lufter/filterlufter/]]></link>
				<description><![CDATA[]]></description>
			</item>
		</items>
	</entry>
	<entry>
		<idname><![CDATA[contrspot12]]></idname>
		<position>
			<left><![CDATA[582]]></left>
			<top><![CDATA[375]]></top>
		</position>
		<items>
			<item>
				<name><![CDATA[USV Netzgeräte]]></name>
				<iconsrc><![CDATA[controlcabinet-28.png]]></iconsrc>
				<link><![CDATA[http://de.rs-online.com/web/c/stromversorgungen-transformatoren/unterbrechungsfreie-stromversorgung-usv/usv-netzgerate/]]></link>
				<description><![CDATA[]]></description>
			</item>
		</items>
	</entry>
	<entry>
		<idname><![CDATA[contrspot13]]></idname>
		<position>
			<left><![CDATA[709]]></left>
			<top><![CDATA[440]]></top>
		</position>
		<items>
			<item>
				<name><![CDATA[Netzteile für DIN Schienentafelmontage]]></name>
				<iconsrc><![CDATA[controlcabinet-29.png]]></iconsrc>
				<link><![CDATA[http://de.rs-online.com/web/c/stromversorgungen-transformatoren/netzteile/netzteile-fur-din-schienen-tafelmontage/]]></link>
				<description><![CDATA[]]></description>
			</item>
		</items>
	</entry>
	<entry>
		<idname><![CDATA[contrspot14]]></idname>
		<position>
			<left><![CDATA[297]]></left>
			<top><![CDATA[259]]></top>
		</position>
		<items>
			<item>
				<name><![CDATA[Bediengeräte Touchpanelversion]]></name>
				<iconsrc><![CDATA[controlcabinet-04.png]]></iconsrc>
				<link><![CDATA[http://de.rs-online.com/web/c/automation/sps-bediengerate-und-datenerfassung/bediengerate-touchpanelversion/]]></link>
				<description><![CDATA[]]></description>
			</item>
		</items>
	</entry>
	<entry>
		<idname><![CDATA[contrspot16]]></idname>
		<position>
			<left><![CDATA[279]]></left>
			<top><![CDATA[352]]></top>
		</position>
		<items>
			<item>
				<name><![CDATA[Zähler]]></name>
				<iconsrc><![CDATA[controlcabinet-05.png]]></iconsrc>
				<link><![CDATA[http://de.rs-online.com/web/c/automation/zeitrelais-und-zahler/zahler/]]></link>
				<description><![CDATA[]]></description>
			</item>
		</items>
	</entry>
	<entry>
		<idname><![CDATA[contrspot17]]></idname>
		<position>
			<left><![CDATA[344]]></left>
			<top><![CDATA[398]]></top>
		</position>
		<items>
			<item>
				<name><![CDATA[PID Temperaturregler]]></name>
				<iconsrc><![CDATA[controlcabinet-06.png]]></iconsrc>
				<link><![CDATA[http://de.rs-online.com/web/c/automation/regeltechnik-und-prozessheizungen/pid-temperaturregler/]]></link>
				<description><![CDATA[]]></description>
			</item>
		</items>
	</entry>
	<entry>
		<idname><![CDATA[contrspot18]]></idname>
		<position>
			<left><![CDATA[270]]></left>
			<top><![CDATA[413]]></top>
		</position>
		<items>
			<item>
				<name><![CDATA[Drucktaster Betätigungselemente]]></name>
				<iconsrc><![CDATA[controlcabinet-07.png]]></iconsrc>
				<link><![CDATA[http://de.rs-online.com/web/c/automation/industrie-drucktaster-leuchtmelder-und-steuerstationen/drucktaster-betatigungselemente/]]></link>
				<description><![CDATA[]]></description>
			</item>
		</items>
	</entry>
</hotspots>
<accessories>
	<entry>
		<name><![CDATA[DIN Schienen]]></name>
		<link><![CDATA[http://de.rs-online.com/web/c/steckverbinder/reihenklemmen-und-anschlussblocke/din-schienen/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Einzeladerleitungen]]></name>
		<link><![CDATA[http://de.rs-online.com/web/c/kabel-leitungen/aderleitungen/einzeladerleitungen/
]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Kabelbinder]]></name>
		<link><![CDATA[http://de.rs-online.com/web/c/kabel-leitungen/kabelzubehoer-kabelbinder-werkzeuge/kabelbinder/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Kabelkanäle]]></name>
		<link><![CDATA[http://de.rs-online.com/web/c/kabel-leitungen/kabelrohre-kabelkanaele-kabelfuehrung/kabelkanaele/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Kabelmakierer]]></name>
		<link><![CDATA[http://de.rs-online.com/web/c/kabel-leitungen/kabelzubehoer-kabelbinder-werkzeuge/kabelmarkierer/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[LED Leuchtröhren]]></name>
		<link><![CDATA[http://de.rs-online.com/web/c/beleuchtung/led-lampen/led-leuchtroehren/
]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Leistungssteckverbinder]]></name>
		<link><![CDATA[http://de.rs-online.com/web/c/steckverbinder/leistungssteckverbinder/leistungssteckverbinder/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Schrumpfschläuche]]></name>
		<link><![CDATA[http://de.rs-online.com/web/c/kabel-leitungen/kabelzubehoer-kabelbinder-werkzeuge/schrumpfschlaeuche/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Schwere Steckverbinder]]></name>
		<link><![CDATA[http://de.rs-online.com/web/c/steckverbinder/leistungssteckverbinder/schwere-steckverbinder/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Standgehäuse]]></name>
		<link><![CDATA[http://de.rs-online.com/web/c/gehause-lagerung-handhabung-transport/gehause/standgehause/]]></link>
		<description><![CDATA[]]></description>
	</entry>
</accessories>
<testandmeasurment>
	<entry>
		<name><![CDATA[Digital Multimeter]]></name>
		<link><![CDATA[http://de.rs-online.com/web/c/pruf-und-messtechnik/multimeter-und-zubehor/digital-multimeter/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Installationstester]]></name>
		<link><![CDATA[http://de.rs-online.com/web/c/pruf-und-messtechnik/installationstester-und-zubehor/installationstester/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[IR Thermometer]]></name>
		<link><![CDATA[http://de.rs-online.com/web/c/pruf-und-messtechnik/temperaturmessgerate/ir-thermometer/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[LAN Messgeräte]]></name>
		<link><![CDATA[http://de.rs-online.com/web/c/pruf-und-messtechnik/kabel-und-netzwerktester/lan-messgerate/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Multifunktionskalibratoren]]></name>
		<link><![CDATA[http://de.rs-online.com/web/c/pruf-und-messtechnik/kalibratoren/multifunktionskalibratoren/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Netzqualitäts- und Leistungsmessgeräte]]></name>
		<link><![CDATA[http://de.rs-online.com/web/c/pruf-und-messtechnik/netzqualitats-und-leistungsmessgerate/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Netzqualitatsanalysatoren]]></name>
		<link><![CDATA[http://de.rs-online.com/web/c/pruf-und-messtechnik/netzqualitats-und-leistungsmessgerate/netzqualitatsanalysatoren/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Wärmebildkameras]]></name>
		<link><![CDATA[http://de.rs-online.com/web/c/pruf-und-messtechnik/temperaturmessgerate/warmebildkameras/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Zangenmessgeräte]]></name>
		<link><![CDATA[http://de.rs-online.com/web/c/pruf-und-messtechnik/elektrische-prufgerate/zangenmessgerate/]]></link>
		<description><![CDATA[]]></description>
	</entry>
</testandmeasurment>
<tools>
	<entry>
		<name><![CDATA[Abisolierer]]></name>
		<link><![CDATA[http://de.rs-online.com/web/c/kabel-leitungen/kabelzubehoer-kabelbinder-werkzeuge/abisolierer/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Akkuschrauber]]></name>
		<link><![CDATA[http://de.rs-online.com/web/c/werkzeuge/akku-werkzeuge/akku-schrauber/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Bohrer & Gewindebohrer Sätze]]></name>
		<link><![CDATA[http://de.rs-online.com/web/c/werkzeuge/gewinde-schneidzeug/bohrer-gewindebohrer-satze/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Crimpwerkzeuge]]></name>
		<link><![CDATA[http://de.rs-online.com/web/c/steckverbinder/steckverbinder-werkzeuge-und-zubehor/crimpwerkzeuge/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Schaltschrankschlüssel]]></name>
		<link><![CDATA[http://de.rs-online.com/web/c/werkzeuge/schraubenschlussel-steckschlussel/schaltschrankschlussel/?searchTerm=schaltschrankschl%C3%BCssel]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Schraubendreher /-sätze]]></name>
		<link><![CDATA[http://de.rs-online.com/web/c/werkzeuge/schraubendreher-schraubenausdreher/schraubendreher-satze/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Wasserwaagen und Neigungsmesser]]></name>
		<link><![CDATA[http://de.rs-online.com/web/c/pruf-und-messtechnik/nivelliergerate-und-winkelmesser/wasserwaagen-und-neigungsmesser/?searchTerm=Wasserwaage]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Zangen Sätze]]></name>
		<link><![CDATA[http://de.rs-online.com/web/c/werkzeuge/zangen/zangen-satze/?sra=p&r=t]]></link>
		<description><![CDATA[]]></description>
	</entry>
</tools>
<rspro>
	<entry>
		<name><![CDATA[Qualität, Leistung und Mehrwert ohne Kompromisse]]></name>
		<link><![CDATA[http://de.rs-online.com/web/b/rs-pro/
]]></link>
		<description><![CDATA[]]></description>
	</entry>
</rspro>
</controlcabinet>
</page>