<?xml version="1.0" encoding="utf-8"?>
<page>
<configuration>
	<cp_title><![CDATA[RS Interactieve<br/>keuzehulp]]></cp_title>
	<cp_subtitle><![CDATA[Ontdek alles wat u nodig heeft]]></cp_subtitle>
	<cp_btngo><![CDATA[Start]]></cp_btngo>
	<cp_chooseyourselection><![CDATA[Kies uw categorie]]></cp_chooseyourselection>
	<cp_titleourservice><![CDATA[Onze services, uw voordelen]]></cp_titleourservice>
	<cp_copyourservice1><![CDATA[Kies uit 500.000 producten bij één enkele leverancier.]]></cp_copyourservice1>
	<cp_copyourservice2><![CDATA[Vind snel de juiste producten met onze website en Technical Support.]]></cp_copyourservice2>
	<cp_copyourservice3><![CDATA[Wij leveren direct de volgende werkdag met ons wereldwijde distributienetwerk.]]></cp_copyourservice3>
	<cp_copyourservice4><![CDATA[Betrouwbare producten van 2.500 toonaangevende merken]]></cp_copyourservice4>
	<cp_copyourservice5><![CDATA[Bepaal zelf de aantallen die u nodig heeft.]]></cp_copyourservice5>
	<cp_copyourservice6><![CDATA[Verzeker uzelf van concurrerende prijzen.]]></cp_copyourservice6>
	<cp_copyourservice7><![CDATA[Door jarenlange samenwerking met onze leveranciers profiteert u van een betrouwbaar productassortiment.]]></cp_copyourservice7>
	<cp_btnselect><![CDATA[Selecteer]]></cp_btnselect>
	<cp_hotspot1><![CDATA[Robottechniek]]></cp_hotspot1>
	<cp_hotspot2><![CDATA[Besturingskast]]></cp_hotspot2>
	<cp_hotspot3><![CDATA[Transportbandsysteem]]></cp_hotspot3>
	<cp_hotspot4><![CDATA[Opslagtank]]></cp_hotspot4>
	<cp_submenu1><![CDATA[Accessoires]]></cp_submenu1>
	<cp_submenu2><![CDATA[Test- en meetapparatuur ]]></cp_submenu2>
	<cp_submenu3><![CDATA[Gereedschap en verbruiksmateriaal]]></cp_submenu3>
	<cp_submenu4><![CDATA[RS Pro]]></cp_submenu4>
</configuration>
<robotics>
<hotspots>
	<entry>
		<idname><![CDATA[robspot2]]></idname>
		<position>
			<left><![CDATA[367]]></left>
			<top><![CDATA[258]]></top>
		</position>
		<items>
			<item>
				<name><![CDATA[Veiligheidsschakelaars]]></name>
				<iconsrc><![CDATA[robotics-02.png]]></iconsrc>
				<link><![CDATA[http://nl.rs-online.com/web/c/automation-control-gear/machine-guarding-safety/solenoid-interlock-switches/]]></link>
				<description><![CDATA[]]></description>
			</item>
		</items>
	</entry>
	<entry>
		<idname><![CDATA[robspot3]]></idname>
		<position>
			<left><![CDATA[429]]></left>
			<top><![CDATA[380]]></top>
		</position>
		<items>
			<item>
				<name><![CDATA[HMI-touchscreens]]></name>
				<iconsrc><![CDATA[robotics-03.png]]></iconsrc>
				<link><![CDATA[http://nl.rs-online.com/web/c/automation-control-gear/plcs-hmi-data-acquisition/touch-screen-hmi-displays/]]></link>
				<description><![CDATA[]]></description>
			</item>
		</items>
	</entry>
	<entry>
		<idname><![CDATA[robspot4]]></idname>
		<position>
			<left><![CDATA[688]]></left>
			<top><![CDATA[254]]></top>
		</position>
		<items>
			<item>
				<name><![CDATA[Noodstopschakelaars]]></name>
				<iconsrc><![CDATA[robotics-04.png]]></iconsrc>
				<link><![CDATA[http://nl.rs-online.com/web/c/automation-control-gear/machine-guarding-safety/emergency-stop-push-buttons/]]></link>
				<description><![CDATA[]]></description>
			</item>
		</items>
	</entry>
	<entry>
		<idname><![CDATA[robspot5]]></idname>
		<position>
			<left><![CDATA[826]]></left>
			<top><![CDATA[123]]></top>
		</position>
		<items>
			<item>
				<name><![CDATA[Beacon Towers]]></name>
				<iconsrc><![CDATA[robotics-05.png]]></iconsrc>
				<link><![CDATA[http://uk.rs-online.com/web/c/automation-control-gear/sounders-beacons/pre-configured-beacon-towers/]]></link>
				<description><![CDATA[]]></description>
			</item>
		</items>
	</entry>
	<entry>
		<idname><![CDATA[robspot6]]></idname>
		<position>
			<left><![CDATA[482]]></left>
			<top><![CDATA[478]]></top>
		</position>
		<items>
			<item>
				<name><![CDATA[Noodstoprelais]]></name>
				<iconsrc><![CDATA[robotics-06.png]]></iconsrc>
				<link><![CDATA[http://nl.rs-online.com/web/c/automation-control-gear/machine-guarding-safety/safety-relays/]]></link>
				<description><![CDATA[]]></description>
			</item>
		</items>
	</entry>
	<entry>
		<idname><![CDATA[robspot7]]></idname>
		<position>
			<left><![CDATA[417]]></left>
			<top><![CDATA[424]]></top>
		</position>
		<items>
			<item>
				<name><![CDATA[Toetsenborden]]></name>
				<iconsrc><![CDATA[robotics-07.png]]></iconsrc>
				<link><![CDATA[http://nl.rs-online.com/web/c/computing-peripherals/keyboards-mice/keyboards/]]></link>
				<description><![CDATA[]]></description>
			</item>
		</items>
	</entry>
	<entry>
		<idname><![CDATA[robspot8]]></idname>
		<position>
			<left><![CDATA[485]]></left>
			<top><![CDATA[407]]></top>
		</position>
		<items>
			<item>
				<name><![CDATA[Sleutelschakelaars]]></name>
				<iconsrc><![CDATA[robotics-08.png]]></iconsrc>
				<link><![CDATA[http://nl.rs-online.com/web/c/switches/key-switches-accessories/key-switches/]]></link>
				<description><![CDATA[]]></description>
			</item>
			<item>
				<name><![CDATA[Drukknopsets]]></name>
				<iconsrc><![CDATA[robotics-09.png]]></iconsrc>
				<link><![CDATA[http://nl.rs-online.com/web/c/automation-control-gear/industrial-push-buttons-pilot-lights-control-stations/push-button-complete-units/]]></link>
				<description><![CDATA[]]></description>
			</item>
		</items>
	</entry>
	<entry>
		<idname><![CDATA[robspot10]]></idname>
		<position>
			<left><![CDATA[457]]></left>
			<top><![CDATA[195]]></top>
		</position>
		<items>
			<item>
				<name><![CDATA[Proces-slangen]]></name>
				<iconsrc><![CDATA[robotics-12.png]]></iconsrc>
				<link><![CDATA[http://nl.rs-online.com/web/c/plumbing-pipeline/pipes-tubing-and-hoses/process-tubing/]]></link>
				<description><![CDATA[]]></description>
			</item>
			<item>
				<name><![CDATA[Optische vezels]]></name>
				<iconsrc><![CDATA[robotics-13.png]]></iconsrc>
				<link><![CDATA[http://nl.rs-online.com/web/c/automation-control-gear/sensors-transducers/fibre-optic-sensors/]]></link>
				<description><![CDATA[]]></description>
			</item>
			<item>
				<name><![CDATA[Pneumatische grijpers]]></name>
				<iconsrc><![CDATA[robotics-10.png]]></iconsrc>
				<link><![CDATA[http://nl.rs-online.com/web/c/pneumatics-hydraulics-power-transmission/pneumatic-cylinders-actuators/pneumatic-grippers/]]></link>
				<description><![CDATA[]]></description>
			</item>
		</items>
	</entry>
	<entry>
		<idname><![CDATA[robspot13]]></idname>
		<position>
			<left><![CDATA[422]]></left>
			<top><![CDATA[94]]></top>
		</position>
		<items>
			<item>
				<name><![CDATA[Pneumatische slangkoppelingen]]></name>
				<iconsrc><![CDATA[robotics-15.png]]></iconsrc>
				<link><![CDATA[http://nl.rs-online.com/web/c/pneumatics-hydraulics-power-transmission/pneumatic-adaptors-fittings-couplings/pneumatic-straight-threaded-to-tube-adaptors/]]></link>
				<description><![CDATA[]]></description>
			</item>
			<item>
				<name><![CDATA[Magneetventielen]]></name>
				<iconsrc><![CDATA[robotics-14.png]]></iconsrc>
				<link><![CDATA[http://nl.rs-online.com/web/c/plumbing-pipeline/valves-taps/solenoid-valves/]]></link>
				<description><![CDATA[]]></description>
			</item>
			<item>
				<name><![CDATA[Servomotoren]]></name>
				<iconsrc><![CDATA[robotics-11.png]]></iconsrc>
				<link><![CDATA[http://nl.rs-online.com/web/c/automation-control-gear/electric-motors-motor-controllers-peripherals/servo-motors/]]></link>
				<description><![CDATA[]]></description>
			</item>
		</items>
	</entry>
</hotspots>
<accessories>
	<entry>
		<name><![CDATA[2-handsbediening]]></name>
		<link><![CDATA[http://nl.rs-online.com/web/c/automation-control-gear/machine-guarding-safety/safety-two-hand-control-switches/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Bureau-units]]></name>
		<link><![CDATA[http://nl.rs-online.com/web/c/enclosures-storage-material-handling/enclosures/consoles-desktop-enclosures/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Drukknoppen]]></name>
		<link><![CDATA[http://nl.rs-online.com/web/c/automation-control-gear/industrial-push-buttons-pilot-lights-control-stations/pilot-light-complete-units/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Druksensor]]></name>
		<link><![CDATA[http://nl.rs-online.com/web/c/automation-control-gear/sensors-transducers/pressure-sensors/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Eindschakelaars]]></name>
		<link><![CDATA[http://nl.rs-online.com/web/c/automation-control-gear/industrial-switches/limit-switches/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Lichtschermen]]></name>
		<link><![CDATA[http://nl.rs-online.com/web/c/automation-control-gear/machine-guarding-safety/light-curtains/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Manometer]]></name>
		<link><![CDATA[http://nl.rs-online.com/web/c/test-measurement/pressure-measurement/analogue-positive-pressure-gauges/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Optische sensoren]]></name>
		<link><![CDATA[http://nl.rs-online.com/web/c/automation-control-gear/sensors-transducers/photoelectric-sensors/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Rotary drives]]></name>
		<link><![CDATA[http://nl.rs-online.com/web/c/pneumatics-hydraulics-power-transmission/pneumatic-cylinders-actuators/rotary-actuators/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Signaalhoorns]]></name>
		<link><![CDATA[http://nl.rs-online.com/web/c/automation-control-gear/sounders-beacons/horns/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Stappenmotoren]]></name>
		<link><![CDATA[http://nl.rs-online.com/web/c/automation-control-gear/electric-motors-motor-controllers-peripherals/stepper-motors/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Stroomcircuit-beveiliging]]></name>
		<link><![CDATA[http://nl.rs-online.com/web/c/automation-control-gear/machine-guarding-safety/safety-controllers/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Veiligheidsdeuren en -hekken]]></name>
		<link><![CDATA[http://nl.rs-online.com/web/c/automation-control-gear/machine-guarding-safety/safety-fencing-doors/?searchTerm=Safety+Fencing+%26+Doors&h=s&sra=oss&redirect-relevancy-data=636F3D3126696E3D4931384E4C446573635461786F6E6F6D794272616E645365617263685465726D266C753D6E6C266D6D3D6D617463687061727469616C6D617826706D3D5E5B5C707B4C7D2D5C707B5A737D5D2B2426706F3D353426736E3D592673743D4B4559574F52445F4D554C54495F414C5048412673633D592677633D4E4F4E45267573743D5361666574792046656E63696E67202620446F6F7273267374613D5361666574792046656E63696E672020446F6F727326]]></link>
		<description><![CDATA[]]></description>
	</entry>
</accessories>
<testandmeasurment>
	<entry>
		<name><![CDATA[Data-loggers]]></name>
		<link><![CDATA[http://nl.rs-online.com/web/c/test-measurement/data-acquisition-logging/data-loggers/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Digitale multimeters]]></name>
		<link><![CDATA[http://nl.rs-online.com/web/c/test-measurement/multimeters-accessories/digital-multimeters/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[IR-thermometers]]></name>
		<link><![CDATA[http://nl.rs-online.com/web/c/test-measurement/temperature-measurement/ir-thermometers/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Kalibratoren]]></name>
		<link><![CDATA[http://nl.rs-online.com/web/c/test-measurement/calibrators/multi-function-calibrators/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Multifunctionele installatietesters]]></name>
		<link><![CDATA[http://nl.rs-online.com/web/c/test-measurement/electrical-installation-testing-accessories/electrical-installation-testers/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Power loggers]]></name>
		<link><![CDATA[http://nl.rs-online.com/web/c/test-measurement/power-measurement/power-quality-analysers/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Spanningsmeters]]></name>
		<link><![CDATA[http://nl.rs-online.com/web/c/test-measurement/electrical-test-equipment/voltage-indicators/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Stroomtangen]]></name>
		<link><![CDATA[http://nl.rs-online.com/web/c/test-measurement/electrical-test-equipment/clampmeters/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Warmtebeeldcamera's]]></name>
		<link><![CDATA[http://nl.rs-online.com/web/c/test-measurement/temperature-measurement/thermal-imaging-cameras/]]></link>
		<description><![CDATA[]]></description>
	</entry>
</testandmeasurment>
<tools>
	<entry>
		<name><![CDATA[Accuboormachines]]></name>
		<link><![CDATA[http://nl.rs-online.com/web/c/tools/cordless-power-tools/cordless-drills-drill-drivers/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Dopsleutelsets]]></name>
		<link><![CDATA[http://nl.rs-online.com/web/c/tools/spanners-sockets/socket-sets/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Momentsleutels]]></name>
		<link><![CDATA[http://nl.rs-online.com/web/c/tools/spanners-sockets/torque-wrenches/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Schroevendraaiersets]]></name>
		<link><![CDATA[http://nl.rs-online.com/web/c/tools/screwdrivers-screw-extractors/screwdriver-sets/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Smeermiddelen]]></name>
		<link><![CDATA[http://nl.rs-online.com/web/c/facilities-cleaning-maintenance/greases-oils-lubricants/lubricants/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Tangensets]]></name>
		<link><![CDATA[http://nl.rs-online.com/web/c/tools/pliers/plier-sets/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Vetspuiten]]></name>
		<link><![CDATA[http://nl.rs-online.com/web/c/tools/manual-grease-guns-accessories/manual-grease-guns/]]></link>
		<description><![CDATA[]]></description>
	</entry>
</tools>
<rspro>
	<entry>
		<name><![CDATA[Kies voor kwaliteit en prestaties zonder compromissen.]]></name>
		<link><![CDATA[http://nl.rs-online.com/web/b/rs-pro/
]]></link>
		<description><![CDATA[]]></description>
	</entry>
</rspro>
</robotics>
<conveyorsystems>
<hotspots>
	<entry>
		<idname><![CDATA[convspot2]]></idname>
		<position>
			<left><![CDATA[209]]></left>
			<top><![CDATA[191]]></top>
		</position>
		<items>
			<item>
				<name><![CDATA[Trekkoordschakelaars]]></name>
				<iconsrc><![CDATA[conveyor-02.png]]></iconsrc>
				<link><![CDATA[http://nl.rs-online.com/web/c/automation-control-gear/machine-guarding-safety/grab-wire-switches/]]></link>
				<description><![CDATA[]]></description>
			</item>
		</items>
	</entry>
	<entry>
		<idname><![CDATA[convspot3]]></idname>
		<position>
			<left><![CDATA[314]]></left>
			<top><![CDATA[161]]></top>
		</position>
		<items>
			<item>
				<name><![CDATA[Led TL-buizen]]></name>
				<iconsrc><![CDATA[conveyor-04.png]]></iconsrc>
				<link><![CDATA[http://nl.rs-online.com/web/c/lighting/led-lamps/led-tube-lights/]]></link>
				<description><![CDATA[]]></description>
			</item>
		</items>
	</entry>
	<entry>
		<idname><![CDATA[convspot4]]></idname>
		<position>
			<left><![CDATA[394]]></left>
			<top><![CDATA[203]]></top>
		</position>
		<items>
			<item>
				<name><![CDATA[Optische sensoren]]></name>
				<iconsrc><![CDATA[conveyor-05.png]]></iconsrc>
				<link><![CDATA[http://nl.rs-online.com/web/c/automation-control-gear/sensors-transducers/photoelectric-sensors/]]></link>
				<description><![CDATA[]]></description>
			</item>
		</items>
	</entry>
	<entry>
		<idname><![CDATA[convspot5]]></idname>
		<position>
			<left><![CDATA[632]]></left>
			<top><![CDATA[245]]></top>
		</position>
		<items>
			<item>
				<name><![CDATA[Lastscheiders]]></name>
				<iconsrc><![CDATA[conveyor-03.png]]></iconsrc>
				<link><![CDATA[http://nl.rs-online.com/web/c/automation-control-gear/industrial-switches/non-fused-switch-disconnectors/]]></link>
				<description><![CDATA[]]></description>
			</item>
		</items>
	</entry>
	<entry>
		<idname><![CDATA[convspot6]]></idname>
		<position>
			<left><![CDATA[488]]></left>
			<top><![CDATA[359]]></top>
		</position>
		<items>
			<item>
				<name><![CDATA[Noodstopschakelaars]]></name>
				<iconsrc><![CDATA[conveyor-06.png]]></iconsrc>
				<link><![CDATA[http://nl.rs-online.com/web/c/automation-control-gear/machine-guarding-safety/emergency-stop-push-buttons/]]></link>
				<description><![CDATA[]]></description>
			</item>
		</items>
	</entry>
	<entry>
		<idname><![CDATA[convspot7]]></idname>
		<position>
			<left><![CDATA[593]]></left>
			<top><![CDATA[348]]></top>
		</position>
		<items>
			<item>
				<name><![CDATA[Frequentieregelaars]]></name>
				<iconsrc><![CDATA[conveyor-07.png]]></iconsrc>
				<link><![CDATA[http://nl.rs-online.com/web/c/automation-control-gear/electric-motors-motor-controllers-peripherals/inverter-drives/]]></link>
				<description><![CDATA[]]></description>
			</item>
		</items>
	</entry>
	<entry>
		<idname><![CDATA[convspot8]]></idname>
		<position>
			<left><![CDATA[651]]></left>
			<top><![CDATA[314]]></top>
		</position>
		<items>
			<item>
				<name><![CDATA[Barcodescanners]]></name>
				<iconsrc><![CDATA[conveyor-08.png]]></iconsrc>
				<link><![CDATA[http://nl.rs-online.com/web/c/automation-control-gear/sensors-transducers/bar-code-readers/]]></link>
				<description><![CDATA[]]></description>
			</item>
		</items>
	</entry>
	<entry>
		<idname><![CDATA[convspot9]]></idname>
		<position>
			<left><![CDATA[720]]></left>
			<top><![CDATA[245]]></top>
		</position>
		<items>
			<item>
				<name><![CDATA[Signaalzuilen]]></name>
				<iconsrc><![CDATA[robotics-05.png]]></iconsrc>
				<link><![CDATA[http://nl.rs-online.com/web/c/automation-control-gear/sounders-beacons/pre-configured-beacon-towers/]]></link>
				<description><![CDATA[]]></description>
			</item>
		</items>
	</entry>
</hotspots>
<accessories>
	<entry>
		<name><![CDATA[AC-motoren]]></name>
		<link><![CDATA[http://nl.rs-online.com/web/c/automation-control-gear/electric-motors-motor-controllers-peripherals/ac-motors/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Behuizingen]]></name>
		<link><![CDATA[http://nl.rs-online.com/web/c/enclosures-storage-material-handling/enclosures/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Capacitieve naderingsschakelaars]]></name>
		<link><![CDATA[http://nl.rs-online.com/web/c/automation-control-gear/sensors-transducers/capacitive-proximity-sensors/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Contactoren]]></name>
		<link><![CDATA[http://nl.rs-online.com/web/c/automation-control-gear/contactors/contactors/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[DOL-motorstarters]]></name>
		<link><![CDATA[http://nl.rs-online.com/web/c/automation-control-gear/electric-motors-motor-controllers-peripherals/dol-star-delta-starters/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Eindschakelaar]]></name>
		<link><![CDATA[http://nl.rs-online.com/web/c/automation-control-gear/machine-guarding-safety/safety-limit-switches/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Encoders]]></name>
		<link><![CDATA[http://nl.rs-online.com/web/c/automation-control-gear/sensors-transducers/rotary-encoders/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Inductieve naderingsschakelaars]]></name>
		<link><![CDATA[http://nl.rs-online.com/web/c/automation-control-gear/sensors-transducers/inductive-proximity-sensors/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Industriële bekabeling]]></name>
		<link><![CDATA[http://nl.rs-online.com/web/c/cables-wires/electrical-power-industrial-cable/multicore-industrial-cable/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Installatieautomaten]]></name>
		<link><![CDATA[http://nl.rs-online.com/web/c/automation-control-gear/circuit-protection-circuit-breakers/mcbs/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Lichtschermen]]></name>
		<link><![CDATA[http://nl.rs-online.com/web/c/automation-control-gear/machine-guarding-safety/light-curtains/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Machine- en inspectieverlichting]]></name>
		<link><![CDATA[http://nl.rs-online.com/web/c/lighting/light-fittings-luminaires/machine-inspection-lights/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Motorbeveiligingsrelais]]></name>
		<link><![CDATA[http://nl.rs-online.com/web/c/automation-control-gear/contactors/contactor-control-relay-overloads/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Schakelkasten]]></name>
		<link><![CDATA[http://nl.rs-online.com/web/c/enclosures-storage-material-handling/enclosures/wall-boxes/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Signaalhoorns]]></name>
		<link><![CDATA[http://nl.rs-online.com/web/c/automation-control-gear/sounders-beacons/horns/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Stroomcircuit-beveiliging]]></name>
		<link><![CDATA[http://nl.rs-online.com/web/c/automation-control-gear/machine-guarding-safety/safety-controllers/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Ultrasone naderingsschakelaars]]></name>
		<link><![CDATA[http://nl.rs-online.com/web/c/automation-control-gear/sensors-transducers/ultrasonic-proximity-sensors/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Veiligheidsdeuren en -hekken]]></name>
		<link><![CDATA[http://nl.rs-online.com/web/c/automation-control-gear/machine-guarding-safety/safety-fencing-doors/?searchTerm=Safety+Fencing+%26+Doors&h=s&sra=oss&redirect-relevancy-data=636F3D3126696E3D4931384E4C446573635461786F6E6F6D794272616E645365617263685465726D266C753D6E6C266D6D3D6D617463687061727469616C6D617826706D3D5E5B5C707B4C7D2D5C707B5A737D5D2B2426706F3D353426736E3D592673743D4B4559574F52445F4D554C54495F414C5048412673633D592677633D4E4F4E45267573743D5361666574792046656E63696E67202620446F6F7273267374613D5361666574792046656E63696E672020446F6F727326]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Vision-sensoren]]></name>
		<link><![CDATA[http://nl.rs-online.com/web/c/automation-control-gear/sensors-transducers/vision-sensors/]]></link>
		<description><![CDATA[]]></description>
	</entry>
</accessories>
<testandmeasurment>
	<entry>
		<name><![CDATA[Digitale multimeters]]></name>
		<link><![CDATA[http://nl.rs-online.com/web/c/test-measurement/multimeters-accessories/digital-multimeters/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[IR-thermometers]]></name>
		<link><![CDATA[http://nl.rs-online.com/web/c/test-measurement/temperature-measurement/ir-thermometers/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Kalibratoren]]></name>
		<link><![CDATA[http://nl.rs-online.com/web/c/test-measurement/calibrators/multi-function-calibrators/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Laser-waterpassen]]></name>
		<link><![CDATA[http://nl.rs-online.com/web/c/test-measurement/level-angular-measurement/laser-levels/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Multifunctionele installatietesters]]></name>
		<link><![CDATA[http://nl.rs-online.com/web/c/test-measurement/electrical-installation-testing-accessories/electrical-installation-testers/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Power loggers]]></name>
		<link><![CDATA[http://nl.rs-online.com/web/c/test-measurement/power-measurement/power-quality-analysers/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Spanningsmeters]]></name>
		<link><![CDATA[http://nl.rs-online.com/web/c/test-measurement/electrical-test-equipment/voltage-indicators/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Stroomtangen]]></name>
		<link><![CDATA[http://nl.rs-online.com/web/c/test-measurement/electrical-test-equipment/clampmeters/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Tachometers]]></name>
		<link><![CDATA[http://nl.rs-online.com/web/c/test-measurement/rotational-measurement/tachometers/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Warmtebeeldcamera's]]></name>
		<link><![CDATA[http://nl.rs-online.com/web/c/test-measurement/temperature-measurement/thermal-imaging-cameras/]]></link>
		<description><![CDATA[]]></description>
	</entry>
</testandmeasurment>
<tools>
	<entry>
		<name><![CDATA[Dopsleutelsets]]></name>
		<link><![CDATA[http://nl.rs-online.com/web/c/tools/spanners-sockets/socket-sets/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Momentsleutels]]></name>
		<link><![CDATA[http://nl.rs-online.com/web/c/tools/spanners-sockets/torque-wrenches/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Poelietrekkers]]></name>
		<link><![CDATA[http://nl.rs-online.com/web/c/tools/pullers-extraction-tools/mechanical-pullers/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Ratels]]></name>
		<link><![CDATA[http://nl.rs-online.com/web/c/tools/spanners-sockets/ratchet-spanners/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Schroevendraaiersets]]></name>
		<link><![CDATA[http://nl.rs-online.com/web/c/tools/screwdrivers-screw-extractors/screwdriver-sets/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Tangensets]]></name>
		<link><![CDATA[http://nl.rs-online.com/web/c/tools/pliers/plier-sets/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Vetspuiten]]></name>
		<link><![CDATA[http://nl.rs-online.com/web/c/tools/manual-grease-guns-accessories/manual-grease-guns/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Waterpassen]]></name>
		<link><![CDATA[http://nl.rs-online.com/web/c/test-measurement/level-angular-measurement/spirit-levels-inclinometers/]]></link>
		<description><![CDATA[]]></description>
	</entry>
</tools>
<rspro>
	<entry>
		<name><![CDATA[Kies voor kwaliteit en prestaties zonder compromissen.]]></name>
		<link><![CDATA[http://nl.rs-online.com/web/b/rs-pro/
]]></link>
		<description><![CDATA[]]></description>
	</entry>
</rspro>
</conveyorsystems>
<storagetank>
<hotspots>
	<entry>
		<idname><![CDATA[storspot2]]></idname>
		<position>
			<left><![CDATA[238]]></left>
			<top><![CDATA[355]]></top>
		</position>
		<items>
			<item>
				<name><![CDATA[Temperatuur-controllers]]></name>
				<iconsrc><![CDATA[storage-02.png]]></iconsrc>
				<link><![CDATA[http://nl.rs-online.com/web/c/automation-control-gear/temperature-control-process-heating/pid-temperature-controllers/]]></link>
				<description><![CDATA[]]></description>
			</item>
		</items>
	</entry>
	<entry>
		<idname><![CDATA[storspot3]]></idname>
		<position>
			<left><![CDATA[337]]></left>
			<top><![CDATA[226]]></top>
		</position>
		<items>
			<item>
				<name><![CDATA[Manometers]]></name>
				<iconsrc><![CDATA[storage-03.png]]></iconsrc>
				<link><![CDATA[http://nl.rs-online.com/web/c/test-measurement/pressure-measurement/analogue-positive-pressure-gauges/]]></link>
				<description><![CDATA[]]></description>
			</item>
		</items>
	</entry>
	<entry>
		<idname><![CDATA[storspot4]]></idname>
		<position>
			<left><![CDATA[372]]></left>
			<top><![CDATA[308]]></top>
		</position>
		<items>
			<item>
				<name><![CDATA[Vloeistofniveau-detectie en vlotterschakelaars]]></name>
				<iconsrc><![CDATA[storage-04.png]]></iconsrc>
				<link><![CDATA[http://nl.rs-online.com/web/c/automation-control-gear/fluid-control-systems/level-sensors-switches/]]></link>
				<description><![CDATA[]]></description>
			</item>
		</items>
	</entry>
	<entry>
		<idname><![CDATA[storspot5]]></idname>
		<position>
			<left><![CDATA[536]]></left>
			<top><![CDATA[86]]></top>
		</position>
		<items>
			<item>
				<name><![CDATA[Druksensoren]]></name>
				<iconsrc><![CDATA[storage-06.png]]></iconsrc>
				<link><![CDATA[http://nl.rs-online.com/web/c/automation-control-gear/sensors-transducers/pressure-sensors/]]></link>
				<description><![CDATA[]]></description>
			</item>
		</items>
	</entry>
	<entry>
		<idname><![CDATA[storspot6]]></idname>
		<position>
			<left><![CDATA[618]]></left>
			<top><![CDATA[42]]></top>
		</position>
		<items>
			<item>
				<name><![CDATA[Drukschakelaars]]></name>
				<iconsrc><![CDATA[storage-07.png]]></iconsrc>
				<link><![CDATA[http://nl.rs-online.com/web/c/automation-control-gear/sensors-transducers/pressure-switches/]]></link>
				<description><![CDATA[]]></description>
			</item>
		</items>
	</entry>
	<entry>
		<idname><![CDATA[storspot7]]></idname>
		<position>
			<left><![CDATA[532]]></left>
			<top><![CDATA[384]]></top>
		</position>
		<items>
			<item>
				<name><![CDATA[Waterdetectie-alarm]]></name>
				<iconsrc><![CDATA[storage-09.png]]></iconsrc>
				<link><![CDATA[http://nl.rs-online.com/web/c/safety-security-esd-control-clean-room/security-alarms-detectors-accessories/water-flood-alarms/]]></link>
				<description><![CDATA[]]></description>
			</item>
		</items>
	</entry>
	<entry>
		<idname><![CDATA[storspot8]]></idname>
		<position>
			<left><![CDATA[670]]></left>
			<top><![CDATA[338]]></top>
		</position>
		<items>
			<item>
				<name><![CDATA[(Druk)krachtsensoren]]></name>
				<iconsrc><![CDATA[storage-10.png]]></iconsrc>
				<link><![CDATA[http://nl.rs-online.com/web/c/automation-control-gear/sensors-transducers/load-cells/]]></link>
				<description><![CDATA[]]></description>
			</item>
		</items>
	</entry>
	<entry>
		<idname><![CDATA[storspot9]]></idname>
		<position>
			<left><![CDATA[724]]></left>
			<top><![CDATA[249]]></top>
		</position>
		<items>
			<item>
				<name><![CDATA[PLC/IO-modules]]></name>
				<iconsrc><![CDATA[storage-11.png]]></iconsrc>
				<link><![CDATA[http://nl.rs-online.com/web/c/automation-control-gear/plcs-hmi-data-acquisition/plc-i-o-modules/]]></link>
				<description><![CDATA[]]></description>
			</item>
		</items>
	</entry>
</hotspots>
<accessories>
	<entry>
		<name><![CDATA[Debietmeters en -schakelaars]]></name>
		<link><![CDATA[http://nl.rs-online.com/web/c/automation-control-gear/fluid-control-systems/flow-sensors-switches-indicators/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Hydraulische filters]]></name>
		<link><![CDATA[http://nl.rs-online.com/web/c/pneumatics-hydraulics-power-transmission/hydraulic-fluids-filtration/hydraulic-filters/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Niveaubewaking]]></name>
		<link><![CDATA[http://nl.rs-online.com/web/c/automation-control-gear/fluid-control-systems/level-controllers/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Pompregelaars]]></name>
		<link><![CDATA[http://nl.rs-online.com/web/c/plumbing-pipeline/central-heating-process-pumps/process-pump-controllers/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Schakelkasten]]></name>
		<link><![CDATA[http://nl.rs-online.com/web/c/enclosures-storage-material-handling/enclosures/wall-boxes/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Thermokoppels]]></name>
		<link><![CDATA[http://nl.rs-online.com/web/c/automation-control-gear/sensors-transducers/thermocouples/]]></link>
		<description><![CDATA[]]></description>
	</entry>
</accessories>
<testandmeasurment>
	<entry>
		<name><![CDATA[Digitale manometers]]></name>
		<link><![CDATA[http://nl.rs-online.com/web/c/test-measurement/pressure-measurement/digital-pressure-meters/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Digitale multimeters]]></name>
		<link><![CDATA[http://nl.rs-online.com/web/c/test-measurement/multimeters-accessories/digital-multimeters/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Gas-detectoren]]></name>
		<link><![CDATA[http://nl.rs-online.com/web/c/test-measurement/air-gas-measurement/gas-detection/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[IR-thermometers]]></name>
		<link><![CDATA[http://nl.rs-online.com/web/c/test-measurement/temperature-measurement/ir-thermometers/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Kalibratoren]]></name>
		<link><![CDATA[http://nl.rs-online.com/web/c/test-measurement/calibrators/multi-function-calibrators/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Power loggers]]></name>
		<link><![CDATA[http://nl.rs-online.com/web/c/test-measurement/power-measurement/power-quality-analysers/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Spanningsmeters]]></name>
		<link><![CDATA[http://nl.rs-online.com/web/c/test-measurement/electrical-test-equipment/voltage-indicators/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Stroomtangen]]></name>
		<link><![CDATA[http://nl.rs-online.com/web/c/test-measurement/electrical-test-equipment/clampmeters/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Warmtebeeldcamera's]]></name>
		<link><![CDATA[http://nl.rs-online.com/web/c/test-measurement/temperature-measurement/thermal-imaging-cameras/]]></link>
		<description><![CDATA[]]></description>
	</entry>
</testandmeasurment>
<tools>
	<entry>
		<name><![CDATA[Accuboormachines]]></name>
		<link><![CDATA[http://nl.rs-online.com/web/c/tools/cordless-power-tools/cordless-drills-drill-drivers/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Draadtapsets]]></name>
		<link><![CDATA[http://nl.rs-online.com/web/c/tools/threading-tools/threading-tap-drill-sets/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Schroevendraaiersets]]></name>
		<link><![CDATA[http://nl.rs-online.com/web/c/tools/screwdrivers-screw-extractors/screwdriver-sets/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Vloeibare pakking]]></name>
		<link><![CDATA[http://nl.rs-online.com/web/c/adhesives-sealants-tapes/sealants/pipe-thread-sealants/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Waterpomptangen]]></name>
		<link><![CDATA[http://nl.rs-online.com/web/c/tools/pliers/water-pump-pliers/
]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Weggooi-handschoenen]]></name>
		<link><![CDATA[http://nl.rs-online.com/web/c/safety-security-esd-control-clean-room/personal-protection-clothing-footwear/disposable-gloves/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Zaklampen]]></name>
		<link><![CDATA[http://nl.rs-online.com/web/c/lighting/torches-handlamps/torches/]]></link>
		<description><![CDATA[]]></description>
	</entry>
</tools>
<rspro>
	<entry>
		<name><![CDATA[Kies voor kwaliteit en prestaties zonder compromissen.]]></name>
		<link><![CDATA[http://nl.rs-online.com/web/b/rs-pro/]]></link>
		<description><![CDATA[]]></description>
	</entry>
</rspro>
</storagetank>
<controlcabinet>
<hotspots>
	<entry>
		<idname><![CDATA[contrspot2]]></idname>
		<position>
			<left><![CDATA[198]]></left>
			<top><![CDATA[285]]></top>
		</position>
		<items>
			<item>
				<name><![CDATA[Hoofdschakelaars]]></name>
				<iconsrc><![CDATA[controlcabinet-02.png]]></iconsrc>
				<link><![CDATA[http://nl.rs-online.com/web/c/automation-control-gear/industrial-switches/non-fused-switch-disconnectors/]]></link>
				<description><![CDATA[]]></description>
			</item>
		</items>
	</entry>
	<entry>
		<idname><![CDATA[contrspot3]]></idname>
		<position>
			<left><![CDATA[495]]></left>
			<top><![CDATA[42]]></top>
		</position>
		<items>
			<item>
				<name><![CDATA[Signaalzuilen]]></name>
				<iconsrc><![CDATA[controlcabinet-10.png]]></iconsrc>
				<link><![CDATA[http://nl.rs-online.com/web/c/automation-control-gear/sounders-beacons/modular-beacon-tower-components/]]></link>
				<description><![CDATA[]]></description>
			</item>
		</items>
	</entry>
	<entry>
		<idname><![CDATA[contrspot4]]></idname>
		<position>
			<left><![CDATA[582]]></left>
			<top><![CDATA[147]]></top>
		</position>
		<items>
			<item>
				<name><![CDATA[Ethernet-aansluitingen]]></name>
				<iconsrc><![CDATA[controlcabinet-11.png]]></iconsrc>
				<link><![CDATA[http://nl.rs-online.com/web/c/automation-control-gear/plcs-hmi-data-acquisition/pc-data-acquisition/]]></link>
				<description><![CDATA[]]></description>
			</item>
			<item>
				<name><![CDATA[Signaalomvormers]]></name>
				<iconsrc><![CDATA[controlcabinet-12.png]]></iconsrc>
				<link><![CDATA[http://nl.rs-online.com/web/c/automation-control-gear/control-relays/signal-conditioning/]]></link>
				<description><![CDATA[]]></description>
			</item>
			<item>
				<name><![CDATA[Omvormers]]></name>
				<iconsrc><![CDATA[controlcabinet-13.png]]></iconsrc>
				<link><![CDATA[http://nl.rs-online.com/web/c/power-supplies-transformers/transformers/din-rail-panel-mount-transformers/]]></link>
				<description><![CDATA[]]></description>
			</item>
		</items>
	</entry>
	<entry>
		<idname><![CDATA[contrspot5]]></idname>
		<position>
			<left><![CDATA[686]]></left>
			<top><![CDATA[196]]></top>
		</position>
		<items>
			<item>
				<name><![CDATA[Industriële hubs en switches]]></name>
				<iconsrc><![CDATA[controlcabinet-14.png]]></iconsrc>
				<link><![CDATA[http://nl.rs-online.com/web/c/computing-peripherals/networking-connectivity/industrial-hubs-switches/
]]></link>
				<description><![CDATA[]]></description>
			</item>
		</items>
	</entry>
	<entry>
		<idname><![CDATA[contrspot6]]></idname>
		<position>
			<left><![CDATA[753]]></left>
			<top><![CDATA[226]]></top>
		</position>
		<items>
			<item>
				<name><![CDATA[Logic-modules]]></name>
				<iconsrc><![CDATA[controlcabinet-15.png]]></iconsrc>
				<link><![CDATA[http://nl.rs-online.com/web/c/automation-control-gear/plcs-hmi-data-acquisition/logic-modules/]]></link>
				<description><![CDATA[]]></description>
			</item>
		</items>
	</entry>
	<entry>
		<idname><![CDATA[contrspot7]]></idname>
		<position>
			<left><![CDATA[605]]></left>
			<top><![CDATA[244]]></top>
		</position>
		<items>
			<item>
				<name><![CDATA[Motorbeveiliging]]></name>
				<iconsrc><![CDATA[controlcabinet-17.png]]></iconsrc>
				<link><![CDATA[http://nl.rs-online.com/web/c/automation-control-gear/electric-motors-motor-controllers-peripherals/motor-protection-circuit-breakers/]]></link>
				<description><![CDATA[]]></description>
			</item>
			<item>
				<name><![CDATA[Contactoren]]></name>
				<iconsrc><![CDATA[controlcabinet-18.png]]></iconsrc>
				<link><![CDATA[http://nl.rs-online.com/web/c/automation-control-gear/contactors/contactors/]]></link>
				<description><![CDATA[]]></description>
			</item>
			<item>
				<name><![CDATA[Frequentieregelaars]]></name>
				<iconsrc><![CDATA[controlcabinet-19.png]]></iconsrc>
				<link><![CDATA[http://nl.rs-online.com/web/c/automation-control-gear/electric-motors-motor-controllers-peripherals/inverter-drives/]]></link>
				<description><![CDATA[]]></description>
			</item>
		</items>
	</entry>
	<entry>
		<idname><![CDATA[contrspot8]]></idname>
		<position>
			<left><![CDATA[688]]></left>
			<top><![CDATA[286]]></top>
		</position>
		<items>
			<item>
				<name><![CDATA[Installatieautomaten]]></name>
				<iconsrc><![CDATA[controlcabinet-20.png]]></iconsrc>
				<link><![CDATA[http://nl.rs-online.com/web/c/automation-control-gear/circuit-protection-circuit-breakers/mcbs/]]></link>
				<description><![CDATA[]]></description>
			</item>
		</items>
	</entry>
	<entry>
		<idname><![CDATA[contrspot9]]></idname>
		<position>
			<left><![CDATA[637]]></left>
			<top><![CDATA[329]]></top>
		</position>
		<items>
			<item>
				<name><![CDATA[Tijdvertragingsrelais]]></name>
				<iconsrc><![CDATA[controlcabinet-23.png]]></iconsrc>
				<link><![CDATA[http://nl.rs-online.com/web/c/automation-control-gear/timers-counters/time-delay-relays/]]></link>
				<description><![CDATA[]]></description>
			</item>
			<item>
				<name><![CDATA[Relaismodules]]></name>
				<iconsrc><![CDATA[controlcabinet-24.png]]></iconsrc>
				<link><![CDATA[http://nl.rs-online.com/web/c/relays/interface-relay-modules-accessories/interface-relay-modules/]]></link>
				<description><![CDATA[]]></description>
			</item>
			<item>
				<name><![CDATA[Noodstoprelais]]></name>
				<iconsrc><![CDATA[controlcabinet-25.png]]></iconsrc>
				<link><![CDATA[http://nl.rs-online.com/web/c/automation-control-gear/machine-guarding-safety/safety-relays/]]></link>
				<description><![CDATA[]]></description>
			</item>
		</items>
	</entry>
	<entry>
		<idname><![CDATA[contrspot10]]></idname>
		<position>
			<left><![CDATA[716]]></left>
			<top><![CDATA[360]]></top>
		</position>
		<items>
			<item>
				<name><![CDATA[PLC's]]></name>
				<iconsrc><![CDATA[controlcabinet-26.png]]></iconsrc>
				<link><![CDATA[http://nl.rs-online.com/web/c/automation-control-gear/plcs-hmi-data-acquisition/plc-cpus/]]></link>
				<description><![CDATA[]]></description>
			</item>
			<item>
				<name><![CDATA[DIN rail-klemmen]]></name>
				<iconsrc><![CDATA[controlcabinet-27.png]]></iconsrc>
				<link><![CDATA[http://nl.rs-online.com/web/c/connectors/terminal-blocks-din-rail-terminals/non-fused-din-rail-terminals/]]></link>
				<description><![CDATA[]]></description>
			</item>
		</items>
	</entry>
	<entry>
		<idname><![CDATA[contrspot11]]></idname>
		<position>
			<left><![CDATA[513]]></left>
			<top><![CDATA[321]]></top>
		</position>
		<items>
			<item>
				<name><![CDATA[Ventilatoren]]></name>
				<iconsrc><![CDATA[controlcabinet-25.png]]></iconsrc>
				<link><![CDATA[http://nl.rs-online.com/web/c/hvac-fans-thermal-management/fans/filter-fans/]]></link>
				<description><![CDATA[]]></description>
			</item>
		</items>
	</entry>
	<entry>
		<idname><![CDATA[contrspot12]]></idname>
		<position>
			<left><![CDATA[582]]></left>
			<top><![CDATA[375]]></top>
		</position>
		<items>
			<item>
				<name><![CDATA[UPS-voedingen]]></name>
				<iconsrc><![CDATA[controlcabinet-28.png]]></iconsrc>
				<link><![CDATA[http://nl.rs-online.com/web/c/power-supplies-transformers/ups-uninterruptible-power-supplies/ups-power-supplies/]]></link>
				<description><![CDATA[]]></description>
			</item>
		</items>
	</entry>
	<entry>
		<idname><![CDATA[contrspot13]]></idname>
		<position>
			<left><![CDATA[709]]></left>
			<top><![CDATA[440]]></top>
		</position>
		<items>
			<item>
				<name><![CDATA[Voedingen]]></name>
				<iconsrc><![CDATA[controlcabinet-29.png]]></iconsrc>
				<link><![CDATA[http://nl.rs-online.com/web/c/power-supplies-transformers/power-supplies-psus/din-rail-panel-mount-power-supplies/]]></link>
				<description><![CDATA[]]></description>
			</item>
		</items>
	</entry>
	<entry>
		<idname><![CDATA[contrspot14]]></idname>
		<position>
			<left><![CDATA[297]]></left>
			<top><![CDATA[259]]></top>
		</position>
		<items>
			<item>
				<name><![CDATA[HMI-touchscreens]]></name>
				<iconsrc><![CDATA[controlcabinet-04.png]]></iconsrc>
				<link><![CDATA[http://nl.rs-online.com/web/c/automation-control-gear/plcs-hmi-data-acquisition/touch-screen-hmi-displays/]]></link>
				<description><![CDATA[]]></description>
			</item>
		</items>
	</entry>
	<entry>
		<idname><![CDATA[contrspot16]]></idname>
		<position>
			<left><![CDATA[279]]></left>
			<top><![CDATA[352]]></top>
		</position>
		<items>
			<item>
				<name><![CDATA[Tellers en timers]]></name>
				<iconsrc><![CDATA[controlcabinet-05.png]]></iconsrc>
				<link><![CDATA[http://nl.rs-online.com/web/c/automation-control-gear/timers-counters/counters/]]></link>
				<description><![CDATA[]]></description>
			</item>
		</items>
	</entry>
	<entry>
		<idname><![CDATA[contrspot17]]></idname>
		<position>
			<left><![CDATA[344]]></left>
			<top><![CDATA[398]]></top>
		</position>
		<items>
			<item>
				<name><![CDATA[Temperatuur-controllers]]></name>
				<iconsrc><![CDATA[controlcabinet-06.png]]></iconsrc>
				<link><![CDATA[http://nl.rs-online.com/web/c/automation-control-gear/temperature-control-process-heating/pid-temperature-controllers/]]></link>
				<description><![CDATA[]]></description>
			</item>
		</items>
	</entry>
	<entry>
		<idname><![CDATA[contrspot18]]></idname>
		<position>
			<left><![CDATA[270]]></left>
			<top><![CDATA[413]]></top>
		</position>
		<items>
			<item>
				<name><![CDATA[Drukknoppen]]></name>
				<iconsrc><![CDATA[controlcabinet-07.png]]></iconsrc>
				<link><![CDATA[http://nl.rs-online.com/web/c/automation-control-gear/industrial-push-buttons-pilot-lights-control-stations/push-button-heads/]]></link>
				<description><![CDATA[]]></description>
			</item>
		</items>
	</entry>
</hotspots>
<accessories>
	<entry>
		<name><![CDATA[Behuizingen]]></name>
		<link><![CDATA[http://nl.rs-online.com/web/c/enclosures-storage-material-handling/enclosures/floor-standing-enclosures/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[DIN rails]]></name>
		<link><![CDATA[http://nl.rs-online.com/web/c/connectors/terminal-blocks-din-rail-terminals/din-rails/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Industriële connectoren]]></name>
		<link><![CDATA[http://nl.rs-online.com/web/c/connectors/power-connectors/heavy-duty-power-connectors/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Kabelbinders]]></name>
		<link><![CDATA[http://nl.rs-online.com/web/c/cables-wires/cable-accessories-ties-tools/cable-ties/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Kabelgoten]]></name>
		<link><![CDATA[http://nl.rs-online.com/web/c/cables-wires/cable-conduit-trunking-routing/cable-trunkings/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Kabelmarkeringen]]></name>
		<link><![CDATA[http://nl.rs-online.com/web/c/cables-wires/cable-accessories-ties-tools/cable-markers/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Krimpkousen]]></name>
		<link><![CDATA[http://nl.rs-online.com/web/c/cables-wires/cable-accessories-ties-tools/heat-shrink-cold-shrink-sleeves/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Led TL-buizen]]></name>
		<link><![CDATA[http://nl.rs-online.com/web/c/lighting/led-lamps/led-tube-lights/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Overige draad]]></name>
		<link><![CDATA[http://nl.rs-online.com/web/c/cables-wires/wire-single-core-cable/hookup-equipment-wire/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Voedingsconnectoren]]></name>
		<link><![CDATA[http://nl.rs-online.com/web/c/connectors/power-connectors/industrial-power-connectors/]]></link>
		<description><![CDATA[]]></description>
	</entry>
</accessories>
<testandmeasurment>
	<entry>
		<name><![CDATA[Digitale multimeters]]></name>
		<link><![CDATA[http://nl.rs-online.com/web/c/test-measurement/multimeters-accessories/digital-multimeters/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[IR-thermometers]]></name>
		<link><![CDATA[http://nl.rs-online.com/web/c/test-measurement/temperature-measurement/ir-thermometers/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Kalibratoren]]></name>
		<link><![CDATA[http://nl.rs-online.com/web/c/test-measurement/calibrators/multi-function-calibrators/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[LAN-testers]]></name>
		<link><![CDATA[http://nl.rs-online.com/web/c/test-measurement/data-cable-network-test-equipment/lan-test-equipment/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Multifunctionele installatietesters]]></name>
		<link><![CDATA[http://nl.rs-online.com/web/c/test-measurement/electrical-installation-testing-accessories/electrical-installation-testers/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Power loggers]]></name>
		<link><![CDATA[http://nl.rs-online.com/web/c/test-measurement/power-measurement/power-quality-analysers/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Spanningsmeters]]></name>
		<link><![CDATA[http://nl.rs-online.com/web/c/test-measurement/electrical-test-equipment/voltage-indicators/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Stroomtangen]]></name>
		<link><![CDATA[http://nl.rs-online.com/web/c/test-measurement/electrical-test-equipment/clampmeters/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Warmtebeeldcamera's]]></name>
		<link><![CDATA[http://nl.rs-online.com/web/c/test-measurement/temperature-measurement/thermal-imaging-cameras/]]></link>
		<description><![CDATA[]]></description>
	</entry>
</testandmeasurment>
<tools>
	<entry>
		<name><![CDATA[Draadtapsets]]></name>
		<link><![CDATA[http://nl.rs-online.com/web/c/tools/threading-tools/threading-tap-drill-sets/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Kabelstrippers]]></name>
		<link><![CDATA[http://nl.rs-online.com/web/c/cables-wires/cable-accessories-ties-tools/cable-strippers/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Krimptangen]]></name>
		<link><![CDATA[http://nl.rs-online.com/web/c/connectors/connector-tools-accessories/crimp-tools/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Schroefmachines]]></name>
		<link><![CDATA[http://nl.rs-online.com/web/c/tools/cordless-power-tools/cordless-screwdrivers/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Schroevendraaiersets]]></name>
		<link><![CDATA[http://nl.rs-online.com/web/c/tools/screwdrivers-screw-extractors/screwdriver-sets/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Tangensets]]></name>
		<link><![CDATA[http://nl.rs-online.com/web/c/tools/pliers/plier-sets/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Universele sleutels]]></name>
		<link><![CDATA[http://nl.rs-online.com/web/c/tools/spanners-sockets/cross-wrenches-control-cabinet-keys/]]></link>
		<description><![CDATA[]]></description>
	</entry>
	<entry>
		<name><![CDATA[Waterpassen]]></name>
		<link><![CDATA[http://nl.rs-online.com/web/c/test-measurement/level-angular-measurement/spirit-levels-inclinometers/]]></link>
		<description><![CDATA[]]></description>
	</entry>
</tools>
<rspro>
	<entry>
		<name><![CDATA[Kies voor kwaliteit en prestaties zonder compromissen.]]></name>
		<link><![CDATA[http://nl.rs-online.com/web/b/rs-pro/]]></link>
		<description><![CDATA[]]></description>
	</entry>
</rspro>
</controlcabinet>
</page>